# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TruckResponseV1
Schema for truck responses, including ID (V1).

    TruckResponseV1(;
        make=nothing,
        model=nothing,
        year=nothing,
        color=nothing,
        vin=nothing,
        mileage=nothing,
        last_service_date=nothing,
        id=nothing,
        bed_length=nothing,
        towing_capacity=nothing,
        payload_capacity=nothing,
        engine_size=nothing,
    )

    - make::String : Make of the vehicle
    - model::String : Model of the vehicle
    - year::Int64 : Year of manufacture
    - color::String : Color of the vehicle
    - vin::String : Vehicle Identification Number (VIN)
    - mileage::Float64 : Current mileage of the vehicle
    - last_service_date::Date
    - id::String : Unique identifier for the vehicle
    - bed_length::Float64 : Length of the truck bed in feet
    - towing_capacity::Float64 : Towing capacity in pounds
    - payload_capacity::Float64 : Maximum payload capacity in pounds
    - engine_size::Float64 : Engine size in liters
"""
Base.@kwdef mutable struct TruckResponseV1 <: OpenAPI.APIModel
    make::Union{Nothing, String} = nothing
    model::Union{Nothing, String} = nothing
    year::Union{Nothing, Int64} = nothing
    color::Union{Nothing, String} = nothing
    vin::Union{Nothing, String} = nothing
    mileage::Union{Nothing, Float64} = nothing
    last_service_date::Union{Nothing, Date} = nothing
    id::Union{Nothing, String} = nothing
    bed_length::Union{Nothing, Float64} = nothing
    towing_capacity::Union{Nothing, Float64} = nothing
    payload_capacity::Union{Nothing, Float64} = nothing
    engine_size::Union{Nothing, Float64} = nothing

    function TruckResponseV1(make, model, year, color, vin, mileage, last_service_date, id, bed_length, towing_capacity, payload_capacity, engine_size, )
        o = new(make, model, year, color, vin, mileage, last_service_date, id, bed_length, towing_capacity, payload_capacity, engine_size, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TruckResponseV1

const _property_types_TruckResponseV1 = Dict{Symbol,String}(Symbol("make")=>"String", Symbol("model")=>"String", Symbol("year")=>"Int64", Symbol("color")=>"String", Symbol("vin")=>"String", Symbol("mileage")=>"Float64", Symbol("last_service_date")=>"Date", Symbol("id")=>"String", Symbol("bed_length")=>"Float64", Symbol("towing_capacity")=>"Float64", Symbol("payload_capacity")=>"Float64", Symbol("engine_size")=>"Float64", )
OpenAPI.property_type(::Type{ TruckResponseV1 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TruckResponseV1[name]))}

function OpenAPI.check_required(o::TruckResponseV1)
    o.make === nothing && (return false)
    o.model === nothing && (return false)
    o.year === nothing && (return false)
    o.color === nothing && (return false)
    o.vin === nothing && (return false)
    o.mileage === nothing && (return false)
    o.id === nothing && (return false)
    o.bed_length === nothing && (return false)
    o.towing_capacity === nothing && (return false)
    o.payload_capacity === nothing && (return false)
    o.engine_size === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TruckResponseV1)
    OpenAPI.validate_property(TruckResponseV1, Symbol("make"), o.make)
    OpenAPI.validate_property(TruckResponseV1, Symbol("model"), o.model)
    OpenAPI.validate_property(TruckResponseV1, Symbol("year"), o.year)
    OpenAPI.validate_property(TruckResponseV1, Symbol("color"), o.color)
    OpenAPI.validate_property(TruckResponseV1, Symbol("vin"), o.vin)
    OpenAPI.validate_property(TruckResponseV1, Symbol("mileage"), o.mileage)
    OpenAPI.validate_property(TruckResponseV1, Symbol("last_service_date"), o.last_service_date)
    OpenAPI.validate_property(TruckResponseV1, Symbol("id"), o.id)
    OpenAPI.validate_property(TruckResponseV1, Symbol("bed_length"), o.bed_length)
    OpenAPI.validate_property(TruckResponseV1, Symbol("towing_capacity"), o.towing_capacity)
    OpenAPI.validate_property(TruckResponseV1, Symbol("payload_capacity"), o.payload_capacity)
    OpenAPI.validate_property(TruckResponseV1, Symbol("engine_size"), o.engine_size)
end

function OpenAPI.validate_property(::Type{ TruckResponseV1 }, name::Symbol, val)





    if name === Symbol("vin")
        OpenAPI.validate_param(name, "TruckResponseV1", :maxLength, val, 17)
        OpenAPI.validate_param(name, "TruckResponseV1", :minLength, val, 17)
    end

    if name === Symbol("mileage")
        OpenAPI.validate_param(name, "TruckResponseV1", :minimum, val, 0.0, false)
    end

    if name === Symbol("last_service_date")
        OpenAPI.validate_param(name, "TruckResponseV1", :format, val, "date")
    end

    if name === Symbol("id")
        OpenAPI.validate_param(name, "TruckResponseV1", :format, val, "uuid")
    end


    if name === Symbol("towing_capacity")
        OpenAPI.validate_param(name, "TruckResponseV1", :maximum, val, 100000.0, false)
        OpenAPI.validate_param(name, "TruckResponseV1", :minimum, val, 0.0, false)
    end


end
