# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CarResponseV2
Schema for car responses, including ID (V2).

    CarResponseV2(;
        make=nothing,
        model=nothing,
        year=nothing,
        color=nothing,
        vin=nothing,
        registration_number=nothing,
        insurance_expiry=nothing,
        is_available=true,
        id=nothing,
        mileage=nothing,
        last_service_date=nothing,
        doors=nothing,
        trunk_capacity=nothing,
        fuel_type=nothing,
        transmission=nothing,
        sunroof=false,
        parking_sensors=false,
    )

    - make::String : Make of the vehicle
    - model::String : Model of the vehicle
    - year::Int64 : Year of manufacture
    - color::String : Color of the vehicle
    - vin::String : Vehicle Identification Number (VIN)
    - registration_number::String : Vehicle registration number
    - insurance_expiry::Date
    - is_available::Bool : Whether the vehicle is available for use
    - id::String : Unique identifier for the vehicle
    - mileage::Float64 : Current mileage of the vehicle
    - last_service_date::Date
    - doors::Int64 : Number of doors
    - trunk_capacity::Float64 : Trunk capacity in cubic feet
    - fuel_type::FuelType : Type of fuel used
    - transmission::TransmissionType : Type of transmission
    - sunroof::Bool : Whether the car has a sunroof
    - parking_sensors::Bool : Whether the car has parking sensors
"""
Base.@kwdef mutable struct CarResponseV2 <: OpenAPI.APIModel
    make::Union{Nothing, String} = nothing
    model::Union{Nothing, String} = nothing
    year::Union{Nothing, Int64} = nothing
    color::Union{Nothing, String} = nothing
    vin::Union{Nothing, String} = nothing
    registration_number::Union{Nothing, String} = nothing
    insurance_expiry::Union{Nothing, Date} = nothing
    is_available::Union{Nothing, Bool} = true
    id::Union{Nothing, String} = nothing
    mileage::Union{Nothing, Float64} = nothing
    last_service_date::Union{Nothing, Date} = nothing
    doors::Union{Nothing, Int64} = nothing
    trunk_capacity::Union{Nothing, Float64} = nothing
    fuel_type = nothing # spec type: Union{ Nothing, FuelType }
    transmission = nothing # spec type: Union{ Nothing, TransmissionType }
    sunroof::Union{Nothing, Bool} = false
    parking_sensors::Union{Nothing, Bool} = false

    function CarResponseV2(make, model, year, color, vin, registration_number, insurance_expiry, is_available, id, mileage, last_service_date, doors, trunk_capacity, fuel_type, transmission, sunroof, parking_sensors, )
        o = new(make, model, year, color, vin, registration_number, insurance_expiry, is_available, id, mileage, last_service_date, doors, trunk_capacity, fuel_type, transmission, sunroof, parking_sensors, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type CarResponseV2

const _property_types_CarResponseV2 = Dict{Symbol,String}(Symbol("make")=>"String", Symbol("model")=>"String", Symbol("year")=>"Int64", Symbol("color")=>"String", Symbol("vin")=>"String", Symbol("registration_number")=>"String", Symbol("insurance_expiry")=>"Date", Symbol("is_available")=>"Bool", Symbol("id")=>"String", Symbol("mileage")=>"Float64", Symbol("last_service_date")=>"Date", Symbol("doors")=>"Int64", Symbol("trunk_capacity")=>"Float64", Symbol("fuel_type")=>"FuelType", Symbol("transmission")=>"TransmissionType", Symbol("sunroof")=>"Bool", Symbol("parking_sensors")=>"Bool", )
OpenAPI.property_type(::Type{ CarResponseV2 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CarResponseV2[name]))}

function OpenAPI.check_required(o::CarResponseV2)
    o.make === nothing && (return false)
    o.model === nothing && (return false)
    o.year === nothing && (return false)
    o.color === nothing && (return false)
    o.vin === nothing && (return false)
    o.registration_number === nothing && (return false)
    o.id === nothing && (return false)
    o.mileage === nothing && (return false)
    o.doors === nothing && (return false)
    o.trunk_capacity === nothing && (return false)
    o.fuel_type === nothing && (return false)
    o.transmission === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::CarResponseV2)
    OpenAPI.validate_property(CarResponseV2, Symbol("make"), o.make)
    OpenAPI.validate_property(CarResponseV2, Symbol("model"), o.model)
    OpenAPI.validate_property(CarResponseV2, Symbol("year"), o.year)
    OpenAPI.validate_property(CarResponseV2, Symbol("color"), o.color)
    OpenAPI.validate_property(CarResponseV2, Symbol("vin"), o.vin)
    OpenAPI.validate_property(CarResponseV2, Symbol("registration_number"), o.registration_number)
    OpenAPI.validate_property(CarResponseV2, Symbol("insurance_expiry"), o.insurance_expiry)
    OpenAPI.validate_property(CarResponseV2, Symbol("is_available"), o.is_available)
    OpenAPI.validate_property(CarResponseV2, Symbol("id"), o.id)
    OpenAPI.validate_property(CarResponseV2, Symbol("mileage"), o.mileage)
    OpenAPI.validate_property(CarResponseV2, Symbol("last_service_date"), o.last_service_date)
    OpenAPI.validate_property(CarResponseV2, Symbol("doors"), o.doors)
    OpenAPI.validate_property(CarResponseV2, Symbol("trunk_capacity"), o.trunk_capacity)
    OpenAPI.validate_property(CarResponseV2, Symbol("fuel_type"), o.fuel_type)
    OpenAPI.validate_property(CarResponseV2, Symbol("transmission"), o.transmission)
    OpenAPI.validate_property(CarResponseV2, Symbol("sunroof"), o.sunroof)
    OpenAPI.validate_property(CarResponseV2, Symbol("parking_sensors"), o.parking_sensors)
end

function OpenAPI.validate_property(::Type{ CarResponseV2 }, name::Symbol, val)





    if name === Symbol("vin")
        OpenAPI.validate_param(name, "CarResponseV2", :maxLength, val, 17)
        OpenAPI.validate_param(name, "CarResponseV2", :minLength, val, 17)
    end


    if name === Symbol("insurance_expiry")
        OpenAPI.validate_param(name, "CarResponseV2", :format, val, "date")
    end


    if name === Symbol("id")
        OpenAPI.validate_param(name, "CarResponseV2", :format, val, "uuid")
    end

    if name === Symbol("mileage")
        OpenAPI.validate_param(name, "CarResponseV2", :minimum, val, 0.0, false)
    end

    if name === Symbol("last_service_date")
        OpenAPI.validate_param(name, "CarResponseV2", :format, val, "date")
    end

    if name === Symbol("doors")
        OpenAPI.validate_param(name, "CarResponseV2", :maximum, val, 5, false)
        OpenAPI.validate_param(name, "CarResponseV2", :minimum, val, 2, false)
    end

    if name === Symbol("trunk_capacity")
        OpenAPI.validate_param(name, "CarResponseV2", :maximum, val, 100.0, false)
        OpenAPI.validate_param(name, "CarResponseV2", :minimum, val, 0.0, false)
    end




end
