# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


if !isdefined(@__MODULE__, :TransmissionType)
    const TransmissionType = String
else
    @warn("Skipping redefinition of TransmissionType to String")
end
