# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""VehicleResponseV2
Base response schema including ID (V2).

    VehicleResponseV2(;
        make=nothing,
        model=nothing,
        year=nothing,
        color=nothing,
        vin=nothing,
        registration_number=nothing,
        insurance_expiry=nothing,
        is_available=true,
        id=nothing,
        mileage=nothing,
        last_service_date=nothing,
    )

    - make::String : Make of the vehicle
    - model::String : Model of the vehicle
    - year::Int64 : Year of manufacture
    - color::String : Color of the vehicle
    - vin::String : Vehicle Identification Number (VIN)
    - registration_number::String : Vehicle registration number
    - insurance_expiry::Date
    - is_available::Bool : Whether the vehicle is available for use
    - id::String : Unique identifier for the vehicle
    - mileage::Float64 : Current mileage of the vehicle
    - last_service_date::Date
"""
Base.@kwdef mutable struct VehicleResponseV2 <: OpenAPI.APIModel
    make::Union{Nothing, String} = nothing
    model::Union{Nothing, String} = nothing
    year::Union{Nothing, Int64} = nothing
    color::Union{Nothing, String} = nothing
    vin::Union{Nothing, String} = nothing
    registration_number::Union{Nothing, String} = nothing
    insurance_expiry::Union{Nothing, Date} = nothing
    is_available::Union{Nothing, Bool} = true
    id::Union{Nothing, String} = nothing
    mileage::Union{Nothing, Float64} = nothing
    last_service_date::Union{Nothing, Date} = nothing

    function VehicleResponseV2(make, model, year, color, vin, registration_number, insurance_expiry, is_available, id, mileage, last_service_date, )
        o = new(make, model, year, color, vin, registration_number, insurance_expiry, is_available, id, mileage, last_service_date, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type VehicleResponseV2

const _property_types_VehicleResponseV2 = Dict{Symbol,String}(Symbol("make")=>"String", Symbol("model")=>"String", Symbol("year")=>"Int64", Symbol("color")=>"String", Symbol("vin")=>"String", Symbol("registration_number")=>"String", Symbol("insurance_expiry")=>"Date", Symbol("is_available")=>"Bool", Symbol("id")=>"String", Symbol("mileage")=>"Float64", Symbol("last_service_date")=>"Date", )
OpenAPI.property_type(::Type{ VehicleResponseV2 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_VehicleResponseV2[name]))}

function OpenAPI.check_required(o::VehicleResponseV2)
    o.make === nothing && (return false)
    o.model === nothing && (return false)
    o.year === nothing && (return false)
    o.color === nothing && (return false)
    o.vin === nothing && (return false)
    o.registration_number === nothing && (return false)
    o.id === nothing && (return false)
    o.mileage === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::VehicleResponseV2)
    OpenAPI.validate_property(VehicleResponseV2, Symbol("make"), o.make)
    OpenAPI.validate_property(VehicleResponseV2, Symbol("model"), o.model)
    OpenAPI.validate_property(VehicleResponseV2, Symbol("year"), o.year)
    OpenAPI.validate_property(VehicleResponseV2, Symbol("color"), o.color)
    OpenAPI.validate_property(VehicleResponseV2, Symbol("vin"), o.vin)
    OpenAPI.validate_property(VehicleResponseV2, Symbol("registration_number"), o.registration_number)
    OpenAPI.validate_property(VehicleResponseV2, Symbol("insurance_expiry"), o.insurance_expiry)
    OpenAPI.validate_property(VehicleResponseV2, Symbol("is_available"), o.is_available)
    OpenAPI.validate_property(VehicleResponseV2, Symbol("id"), o.id)
    OpenAPI.validate_property(VehicleResponseV2, Symbol("mileage"), o.mileage)
    OpenAPI.validate_property(VehicleResponseV2, Symbol("last_service_date"), o.last_service_date)
end

function OpenAPI.validate_property(::Type{ VehicleResponseV2 }, name::Symbol, val)





    if name === Symbol("vin")
        OpenAPI.validate_param(name, "VehicleResponseV2", :maxLength, val, 17)
        OpenAPI.validate_param(name, "VehicleResponseV2", :minLength, val, 17)
    end


    if name === Symbol("insurance_expiry")
        OpenAPI.validate_param(name, "VehicleResponseV2", :format, val, "date")
    end


    if name === Symbol("id")
        OpenAPI.validate_param(name, "VehicleResponseV2", :format, val, "uuid")
    end

    if name === Symbol("mileage")
        OpenAPI.validate_param(name, "VehicleResponseV2", :minimum, val, 0.0, false)
    end

    if name === Symbol("last_service_date")
        OpenAPI.validate_param(name, "VehicleResponseV2", :format, val, "date")
    end
end
