# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""Vehicle_1

    Vehicle1(; value=nothing)
"""
mutable struct Vehicle1 <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ CarCreateV2, TruckCreateV2 }
    Vehicle1() = new()
    Vehicle1(value) = new(value)
end # type Vehicle1

function OpenAPI.property_type(::Type{ Vehicle1 }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(Vehicle1, name)
end
