# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""Vehicle

    Vehicle(; value=nothing)
"""
mutable struct Vehicle <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ CarCreateV1, TruckCreateV1 }
    Vehicle() = new()
    Vehicle(value) = new(value)
end # type Vehicle

function OpenAPI.property_type(::Type{ Vehicle }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(Vehicle, name)
end
