# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TruckCreateV2
Schema for creating a truck (V2).

    TruckCreateV2(;
        make=nothing,
        model=nothing,
        year=nothing,
        color=nothing,
        vin=nothing,
        registration_number=nothing,
        insurance_expiry=nothing,
        is_available=true,
        bed_length=nothing,
        towing_capacity=nothing,
        payload_capacity=nothing,
        engine_size=nothing,
        four_wheel_drive=false,
        bed_liner=false,
    )

    - make::String : Make of the vehicle
    - model::String : Model of the vehicle
    - year::Int64 : Year of manufacture
    - color::String : Color of the vehicle
    - vin::String : Vehicle Identification Number (VIN)
    - registration_number::String : Vehicle registration number
    - insurance_expiry::Date
    - is_available::Bool : Whether the vehicle is available for use
    - bed_length::Float64 : Length of the truck bed in feet
    - towing_capacity::Float64 : Towing capacity in pounds
    - payload_capacity::Float64 : Maximum payload capacity in pounds
    - engine_size::Float64 : Engine size in liters
    - four_wheel_drive::Bool : Whether the truck has four-wheel drive
    - bed_liner::Bool : Whether the truck has a bed liner
"""
Base.@kwdef mutable struct TruckCreateV2 <: OpenAPI.APIModel
    make::Union{Nothing, String} = nothing
    model::Union{Nothing, String} = nothing
    year::Union{Nothing, Int64} = nothing
    color::Union{Nothing, String} = nothing
    vin::Union{Nothing, String} = nothing
    registration_number::Union{Nothing, String} = nothing
    insurance_expiry::Union{Nothing, Date} = nothing
    is_available::Union{Nothing, Bool} = true
    bed_length::Union{Nothing, Float64} = nothing
    towing_capacity::Union{Nothing, Float64} = nothing
    payload_capacity::Union{Nothing, Float64} = nothing
    engine_size::Union{Nothing, Float64} = nothing
    four_wheel_drive::Union{Nothing, Bool} = false
    bed_liner::Union{Nothing, Bool} = false

    function TruckCreateV2(make, model, year, color, vin, registration_number, insurance_expiry, is_available, bed_length, towing_capacity, payload_capacity, engine_size, four_wheel_drive, bed_liner, )
        o = new(make, model, year, color, vin, registration_number, insurance_expiry, is_available, bed_length, towing_capacity, payload_capacity, engine_size, four_wheel_drive, bed_liner, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TruckCreateV2

const _property_types_TruckCreateV2 = Dict{Symbol,String}(Symbol("make")=>"String", Symbol("model")=>"String", Symbol("year")=>"Int64", Symbol("color")=>"String", Symbol("vin")=>"String", Symbol("registration_number")=>"String", Symbol("insurance_expiry")=>"Date", Symbol("is_available")=>"Bool", Symbol("bed_length")=>"Float64", Symbol("towing_capacity")=>"Float64", Symbol("payload_capacity")=>"Float64", Symbol("engine_size")=>"Float64", Symbol("four_wheel_drive")=>"Bool", Symbol("bed_liner")=>"Bool", )
OpenAPI.property_type(::Type{ TruckCreateV2 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TruckCreateV2[name]))}

function OpenAPI.check_required(o::TruckCreateV2)
    o.make === nothing && (return false)
    o.model === nothing && (return false)
    o.year === nothing && (return false)
    o.color === nothing && (return false)
    o.vin === nothing && (return false)
    o.registration_number === nothing && (return false)
    o.bed_length === nothing && (return false)
    o.towing_capacity === nothing && (return false)
    o.payload_capacity === nothing && (return false)
    o.engine_size === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TruckCreateV2)
    OpenAPI.validate_property(TruckCreateV2, Symbol("make"), o.make)
    OpenAPI.validate_property(TruckCreateV2, Symbol("model"), o.model)
    OpenAPI.validate_property(TruckCreateV2, Symbol("year"), o.year)
    OpenAPI.validate_property(TruckCreateV2, Symbol("color"), o.color)
    OpenAPI.validate_property(TruckCreateV2, Symbol("vin"), o.vin)
    OpenAPI.validate_property(TruckCreateV2, Symbol("registration_number"), o.registration_number)
    OpenAPI.validate_property(TruckCreateV2, Symbol("insurance_expiry"), o.insurance_expiry)
    OpenAPI.validate_property(TruckCreateV2, Symbol("is_available"), o.is_available)
    OpenAPI.validate_property(TruckCreateV2, Symbol("bed_length"), o.bed_length)
    OpenAPI.validate_property(TruckCreateV2, Symbol("towing_capacity"), o.towing_capacity)
    OpenAPI.validate_property(TruckCreateV2, Symbol("payload_capacity"), o.payload_capacity)
    OpenAPI.validate_property(TruckCreateV2, Symbol("engine_size"), o.engine_size)
    OpenAPI.validate_property(TruckCreateV2, Symbol("four_wheel_drive"), o.four_wheel_drive)
    OpenAPI.validate_property(TruckCreateV2, Symbol("bed_liner"), o.bed_liner)
end

function OpenAPI.validate_property(::Type{ TruckCreateV2 }, name::Symbol, val)





    if name === Symbol("vin")
        OpenAPI.validate_param(name, "TruckCreateV2", :maxLength, val, 17)
        OpenAPI.validate_param(name, "TruckCreateV2", :minLength, val, 17)
    end


    if name === Symbol("insurance_expiry")
        OpenAPI.validate_param(name, "TruckCreateV2", :format, val, "date")
    end



    if name === Symbol("towing_capacity")
        OpenAPI.validate_param(name, "TruckCreateV2", :maximum, val, 100000.0, false)
        OpenAPI.validate_param(name, "TruckCreateV2", :minimum, val, 0.0, false)
    end




end
