# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""ValidationError_loc_inner

    ValidationErrorLocInner(; value=nothing)
"""
mutable struct ValidationErrorLocInner <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Int64, String }
    ValidationErrorLocInner() = new()
    ValidationErrorLocInner(value) = new(value)
end # type ValidationErrorLocInner

function OpenAPI.property_type(::Type{ ValidationErrorLocInner }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(ValidationErrorLocInner, name)
end
