/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "CarCreateV2.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

CarCreateV2::CarCreateV2()
{
    m_Make = "";
    m_Model = "";
    m_Year = 0;
    m_Color = "";
    m_Vin = "";
    m_Registration_number = "";
    m_Insurance_expiryIsSet = false;
    m_Is_available = true;
    m_Is_availableIsSet = false;
    m_Doors = 0;
    m_Trunk_capacity = 0.0;
    m_Sunroof = false;
    m_SunroofIsSet = false;
    m_Parking_sensors = false;
    m_Parking_sensorsIsSet = false;
    
}

void CarCreateV2::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool CarCreateV2::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool CarCreateV2::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "CarCreateV2" : pathPrefix;

                         
    
    /* Vin */ {
        const std::string& value = m_Vin;
        const std::string currentValuePath = _pathPrefix + ".vin";
                
        
        if (value.length() < 17)
        {
            success = false;
            msg << currentValuePath << ": must be at least 17 characters long;";
        }
        if (value.length() > 17)
        {
            success = false;
            msg << currentValuePath << ": must be at most 17 characters long;";
        }

    }
                     
    
    /* Doors */ {
        const int32_t& value = m_Doors;
        const std::string currentValuePath = _pathPrefix + ".doors";
                
        
        if (value < 2)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 2;";
        }
        if (value > 5)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 5;";
        }

    }
         
    
    /* Trunk_capacity */ {
        const double& value = m_Trunk_capacity;
        const std::string currentValuePath = _pathPrefix + ".trunkCapacity";
                
        
        if (value < 0.0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0.0;";
        }
        if (value > 100.0)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 100.0;";
        }

    }
                    
    return success;
}

bool CarCreateV2::operator==(const CarCreateV2& rhs) const
{
    return
    
    
    (getMake() == rhs.getMake())
     &&
    
    (getModel() == rhs.getModel())
     &&
    
    (getYear() == rhs.getYear())
     &&
    
    (getColor() == rhs.getColor())
     &&
    
    (getVin() == rhs.getVin())
     &&
    
    (getRegistrationNumber() == rhs.getRegistrationNumber())
     &&
    
    
    ((!insuranceExpiryIsSet() && !rhs.insuranceExpiryIsSet()) || (insuranceExpiryIsSet() && rhs.insuranceExpiryIsSet() && getInsuranceExpiry() == rhs.getInsuranceExpiry())) &&
    
    
    ((!isAvailableIsSet() && !rhs.isAvailableIsSet()) || (isAvailableIsSet() && rhs.isAvailableIsSet() && isIsAvailable() == rhs.isIsAvailable())) &&
    
    (getDoors() == rhs.getDoors())
     &&
    
    (getTrunkCapacity() == rhs.getTrunkCapacity())
     &&
    
    (getFuelType() == rhs.getFuelType())
     &&
    
    (getTransmission() == rhs.getTransmission())
     &&
    
    
    ((!sunroofIsSet() && !rhs.sunroofIsSet()) || (sunroofIsSet() && rhs.sunroofIsSet() && isSunroof() == rhs.isSunroof())) &&
    
    
    ((!parkingSensorsIsSet() && !rhs.parkingSensorsIsSet()) || (parkingSensorsIsSet() && rhs.parkingSensorsIsSet() && isParkingSensors() == rhs.isParkingSensors()))
    
    ;
}

bool CarCreateV2::operator!=(const CarCreateV2& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const CarCreateV2& o)
{
    j = nlohmann::json::object();
    j["make"] = o.m_Make;
    j["model"] = o.m_Model;
    j["year"] = o.m_Year;
    j["color"] = o.m_Color;
    j["vin"] = o.m_Vin;
    j["registration_number"] = o.m_Registration_number;
    if(o.insuranceExpiryIsSet())
        j["insurance_expiry"] = o.m_Insurance_expiry;
    if(o.isAvailableIsSet())
        j["is_available"] = o.m_Is_available;
    j["doors"] = o.m_Doors;
    j["trunk_capacity"] = o.m_Trunk_capacity;
    j["fuel_type"] = o.m_Fuel_type;
    j["transmission"] = o.m_Transmission;
    if(o.sunroofIsSet())
        j["sunroof"] = o.m_Sunroof;
    if(o.parkingSensorsIsSet())
        j["parking_sensors"] = o.m_Parking_sensors;
    
}

void from_json(const nlohmann::json& j, CarCreateV2& o)
{
    j.at("make").get_to(o.m_Make);
    j.at("model").get_to(o.m_Model);
    j.at("year").get_to(o.m_Year);
    j.at("color").get_to(o.m_Color);
    j.at("vin").get_to(o.m_Vin);
    j.at("registration_number").get_to(o.m_Registration_number);
    if(j.find("insurance_expiry") != j.end())
    {
        j.at("insurance_expiry").get_to(o.m_Insurance_expiry);
        o.m_Insurance_expiryIsSet = true;
    } 
    if(j.find("is_available") != j.end())
    {
        j.at("is_available").get_to(o.m_Is_available);
        o.m_Is_availableIsSet = true;
    } 
    j.at("doors").get_to(o.m_Doors);
    j.at("trunk_capacity").get_to(o.m_Trunk_capacity);
    j.at("fuel_type").get_to(o.m_Fuel_type);
    j.at("transmission").get_to(o.m_Transmission);
    if(j.find("sunroof") != j.end())
    {
        j.at("sunroof").get_to(o.m_Sunroof);
        o.m_SunroofIsSet = true;
    } 
    if(j.find("parking_sensors") != j.end())
    {
        j.at("parking_sensors").get_to(o.m_Parking_sensors);
        o.m_Parking_sensorsIsSet = true;
    } 
    
}

std::string CarCreateV2::getMake() const
{
    return m_Make;
}
void CarCreateV2::setMake(std::string const& value)
{
    m_Make = value;
}
std::string CarCreateV2::getModel() const
{
    return m_Model;
}
void CarCreateV2::setModel(std::string const& value)
{
    m_Model = value;
}
int32_t CarCreateV2::getYear() const
{
    return m_Year;
}
void CarCreateV2::setYear(int32_t const value)
{
    m_Year = value;
}
std::string CarCreateV2::getColor() const
{
    return m_Color;
}
void CarCreateV2::setColor(std::string const& value)
{
    m_Color = value;
}
std::string CarCreateV2::getVin() const
{
    return m_Vin;
}
void CarCreateV2::setVin(std::string const& value)
{
    m_Vin = value;
}
std::string CarCreateV2::getRegistrationNumber() const
{
    return m_Registration_number;
}
void CarCreateV2::setRegistrationNumber(std::string const& value)
{
    m_Registration_number = value;
}
std::string CarCreateV2::getInsuranceExpiry() const
{
    return m_Insurance_expiry;
}
void CarCreateV2::setInsuranceExpiry(std::string const& value)
{
    m_Insurance_expiry = value;
    m_Insurance_expiryIsSet = true;
}
bool CarCreateV2::insuranceExpiryIsSet() const
{
    return m_Insurance_expiryIsSet;
}
void CarCreateV2::unsetInsurance_expiry()
{
    m_Insurance_expiryIsSet = false;
}
bool CarCreateV2::isIsAvailable() const
{
    return m_Is_available;
}
void CarCreateV2::setIsAvailable(bool const value)
{
    m_Is_available = value;
    m_Is_availableIsSet = true;
}
bool CarCreateV2::isAvailableIsSet() const
{
    return m_Is_availableIsSet;
}
void CarCreateV2::unsetIs_available()
{
    m_Is_availableIsSet = false;
}
int32_t CarCreateV2::getDoors() const
{
    return m_Doors;
}
void CarCreateV2::setDoors(int32_t const value)
{
    m_Doors = value;
}
double CarCreateV2::getTrunkCapacity() const
{
    return m_Trunk_capacity;
}
void CarCreateV2::setTrunkCapacity(double const value)
{
    m_Trunk_capacity = value;
}
org::openapitools::server::model::FuelType CarCreateV2::getFuelType() const
{
    return m_Fuel_type;
}
void CarCreateV2::setFuelType(org::openapitools::server::model::FuelType const& value)
{
    m_Fuel_type = value;
}
org::openapitools::server::model::TransmissionType CarCreateV2::getTransmission() const
{
    return m_Transmission;
}
void CarCreateV2::setTransmission(org::openapitools::server::model::TransmissionType const& value)
{
    m_Transmission = value;
}
bool CarCreateV2::isSunroof() const
{
    return m_Sunroof;
}
void CarCreateV2::setSunroof(bool const value)
{
    m_Sunroof = value;
    m_SunroofIsSet = true;
}
bool CarCreateV2::sunroofIsSet() const
{
    return m_SunroofIsSet;
}
void CarCreateV2::unsetSunroof()
{
    m_SunroofIsSet = false;
}
bool CarCreateV2::isParkingSensors() const
{
    return m_Parking_sensors;
}
void CarCreateV2::setParkingSensors(bool const value)
{
    m_Parking_sensors = value;
    m_Parking_sensorsIsSet = true;
}
bool CarCreateV2::parkingSensorsIsSet() const
{
    return m_Parking_sensorsIsSet;
}
void CarCreateV2::unsetParking_sensors()
{
    m_Parking_sensorsIsSet = false;
}


} // namespace org::openapitools::server::model

