/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * CarCreateV1.h
 *
 * Schema for creating a car (V1).
 */

#ifndef CarCreateV1_H_
#define CarCreateV1_H_


#include "FuelType.h"
#include <string>
#include "TransmissionType.h"
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Schema for creating a car (V1).
/// </summary>
class  CarCreateV1
{
public:
    CarCreateV1();
    virtual ~CarCreateV1() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const CarCreateV1& rhs) const;
    bool operator!=(const CarCreateV1& rhs) const;

    /////////////////////////////////////////////
    /// CarCreateV1 members

    /// <summary>
    /// Make of the vehicle
    /// </summary>
    std::string getMake() const;
    void setMake(std::string const& value);
    /// <summary>
    /// Model of the vehicle
    /// </summary>
    std::string getModel() const;
    void setModel(std::string const& value);
    /// <summary>
    /// Year of manufacture
    /// </summary>
    int32_t getYear() const;
    void setYear(int32_t const value);
    /// <summary>
    /// Color of the vehicle
    /// </summary>
    std::string getColor() const;
    void setColor(std::string const& value);
    /// <summary>
    /// Vehicle Identification Number (VIN)
    /// </summary>
    std::string getVin() const;
    void setVin(std::string const& value);
    /// <summary>
    /// Current mileage of the vehicle
    /// </summary>
    double getMileage() const;
    void setMileage(double const value);
    /// <summary>
    /// 
    /// </summary>
    std::string getLastServiceDate() const;
    void setLastServiceDate(std::string const& value);
    bool lastServiceDateIsSet() const;
    void unsetLast_service_date();
    /// <summary>
    /// Number of doors
    /// </summary>
    int32_t getDoors() const;
    void setDoors(int32_t const value);
    /// <summary>
    /// Trunk capacity in cubic feet
    /// </summary>
    double getTrunkCapacity() const;
    void setTrunkCapacity(double const value);
    /// <summary>
    /// Type of fuel used
    /// </summary>
    org::openapitools::server::model::FuelType getFuelType() const;
    void setFuelType(org::openapitools::server::model::FuelType const& value);
    /// <summary>
    /// Type of transmission
    /// </summary>
    org::openapitools::server::model::TransmissionType getTransmission() const;
    void setTransmission(org::openapitools::server::model::TransmissionType const& value);

    friend  void to_json(nlohmann::json& j, const CarCreateV1& o);
    friend  void from_json(const nlohmann::json& j, CarCreateV1& o);
protected:
    std::string m_Make;

    std::string m_Model;

    int32_t m_Year;

    std::string m_Color;

    std::string m_Vin;

    double m_Mileage;

    std::string m_Last_service_date;
    bool m_Last_service_dateIsSet;
    int32_t m_Doors;

    double m_Trunk_capacity;

    org::openapitools::server::model::FuelType m_Fuel_type;

    org::openapitools::server::model::TransmissionType m_Transmission;

    
};

} // namespace org::openapitools::server::model

#endif /* CarCreateV1_H_ */
