/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "CarResponseV1.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

CarResponseV1::CarResponseV1()
{
    m_Make = "";
    m_Model = "";
    m_Year = 0;
    m_Color = "";
    m_Vin = "";
    m_Mileage = 0.0;
    m_Last_service_dateIsSet = false;
    m_Id = "";
    m_Doors = 0;
    m_Trunk_capacity = 0.0;
    
}

void CarResponseV1::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool CarResponseV1::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool CarResponseV1::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "CarResponseV1" : pathPrefix;

                 
    
    /* Year */ {
        const int32_t& value = m_Year;
        const std::string currentValuePath = _pathPrefix + ".year";
                
        
        if (value < 1950)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 1950;";
        }
        if (value > 2025)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 2025;";
        }

    }
             
    
    /* Vin */ {
        const std::string& value = m_Vin;
        const std::string currentValuePath = _pathPrefix + ".vin";
                
        
        if (value.length() < 17)
        {
            success = false;
            msg << currentValuePath << ": must be at least 17 characters long;";
        }
        if (value.length() > 17)
        {
            success = false;
            msg << currentValuePath << ": must be at most 17 characters long;";
        }

    }
         
    
    /* Mileage */ {
        const double& value = m_Mileage;
        const std::string currentValuePath = _pathPrefix + ".mileage";
                
        
        if (value < 0.0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0.0;";
        }

    }
                 
    
    /* Doors */ {
        const int32_t& value = m_Doors;
        const std::string currentValuePath = _pathPrefix + ".doors";
                
        
        if (value < 2)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 2;";
        }
        if (value > 5)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 5;";
        }

    }
         
    
    /* Trunk_capacity */ {
        const double& value = m_Trunk_capacity;
        const std::string currentValuePath = _pathPrefix + ".trunkCapacity";
                
        
        if (value < 0.0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0.0;";
        }
        if (value > 100.0)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 100.0;";
        }

    }
            
    return success;
}

bool CarResponseV1::operator==(const CarResponseV1& rhs) const
{
    return
    
    
    (getMake() == rhs.getMake())
     &&
    
    (getModel() == rhs.getModel())
     &&
    
    (getYear() == rhs.getYear())
     &&
    
    (getColor() == rhs.getColor())
     &&
    
    (getVin() == rhs.getVin())
     &&
    
    (getMileage() == rhs.getMileage())
     &&
    
    
    ((!lastServiceDateIsSet() && !rhs.lastServiceDateIsSet()) || (lastServiceDateIsSet() && rhs.lastServiceDateIsSet() && getLastServiceDate() == rhs.getLastServiceDate())) &&
    
    (getId() == rhs.getId())
     &&
    
    (getDoors() == rhs.getDoors())
     &&
    
    (getTrunkCapacity() == rhs.getTrunkCapacity())
     &&
    
    (getFuelType() == rhs.getFuelType())
     &&
    
    (getTransmission() == rhs.getTransmission())
    
    
    ;
}

bool CarResponseV1::operator!=(const CarResponseV1& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const CarResponseV1& o)
{
    j = nlohmann::json::object();
    j["make"] = o.m_Make;
    j["model"] = o.m_Model;
    j["year"] = o.m_Year;
    j["color"] = o.m_Color;
    j["vin"] = o.m_Vin;
    j["mileage"] = o.m_Mileage;
    if(o.lastServiceDateIsSet())
        j["last_service_date"] = o.m_Last_service_date;
    j["id"] = o.m_Id;
    j["doors"] = o.m_Doors;
    j["trunk_capacity"] = o.m_Trunk_capacity;
    j["fuel_type"] = o.m_Fuel_type;
    j["transmission"] = o.m_Transmission;
    
}

void from_json(const nlohmann::json& j, CarResponseV1& o)
{
    j.at("make").get_to(o.m_Make);
    j.at("model").get_to(o.m_Model);
    j.at("year").get_to(o.m_Year);
    j.at("color").get_to(o.m_Color);
    j.at("vin").get_to(o.m_Vin);
    j.at("mileage").get_to(o.m_Mileage);
    if(j.find("last_service_date") != j.end())
    {
        j.at("last_service_date").get_to(o.m_Last_service_date);
        o.m_Last_service_dateIsSet = true;
    } 
    j.at("id").get_to(o.m_Id);
    j.at("doors").get_to(o.m_Doors);
    j.at("trunk_capacity").get_to(o.m_Trunk_capacity);
    j.at("fuel_type").get_to(o.m_Fuel_type);
    j.at("transmission").get_to(o.m_Transmission);
    
}

std::string CarResponseV1::getMake() const
{
    return m_Make;
}
void CarResponseV1::setMake(std::string const& value)
{
    m_Make = value;
}
std::string CarResponseV1::getModel() const
{
    return m_Model;
}
void CarResponseV1::setModel(std::string const& value)
{
    m_Model = value;
}
int32_t CarResponseV1::getYear() const
{
    return m_Year;
}
void CarResponseV1::setYear(int32_t const value)
{
    m_Year = value;
}
std::string CarResponseV1::getColor() const
{
    return m_Color;
}
void CarResponseV1::setColor(std::string const& value)
{
    m_Color = value;
}
std::string CarResponseV1::getVin() const
{
    return m_Vin;
}
void CarResponseV1::setVin(std::string const& value)
{
    m_Vin = value;
}
double CarResponseV1::getMileage() const
{
    return m_Mileage;
}
void CarResponseV1::setMileage(double const value)
{
    m_Mileage = value;
}
std::string CarResponseV1::getLastServiceDate() const
{
    return m_Last_service_date;
}
void CarResponseV1::setLastServiceDate(std::string const& value)
{
    m_Last_service_date = value;
    m_Last_service_dateIsSet = true;
}
bool CarResponseV1::lastServiceDateIsSet() const
{
    return m_Last_service_dateIsSet;
}
void CarResponseV1::unsetLast_service_date()
{
    m_Last_service_dateIsSet = false;
}
std::string CarResponseV1::getId() const
{
    return m_Id;
}
void CarResponseV1::setId(std::string const& value)
{
    m_Id = value;
}
int32_t CarResponseV1::getDoors() const
{
    return m_Doors;
}
void CarResponseV1::setDoors(int32_t const value)
{
    m_Doors = value;
}
double CarResponseV1::getTrunkCapacity() const
{
    return m_Trunk_capacity;
}
void CarResponseV1::setTrunkCapacity(double const value)
{
    m_Trunk_capacity = value;
}
org::openapitools::server::model::FuelType CarResponseV1::getFuelType() const
{
    return m_Fuel_type;
}
void CarResponseV1::setFuelType(org::openapitools::server::model::FuelType const& value)
{
    m_Fuel_type = value;
}
org::openapitools::server::model::TransmissionType CarResponseV1::getTransmission() const
{
    return m_Transmission;
}
void CarResponseV1::setTransmission(org::openapitools::server::model::TransmissionType const& value)
{
    m_Transmission = value;
}


} // namespace org::openapitools::server::model

