/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "CarResponseV2.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

CarResponseV2::CarResponseV2()
{
    m_Make = "";
    m_Model = "";
    m_Year = 0;
    m_Color = "";
    m_Vin = "";
    m_Registration_number = "";
    m_Insurance_expiryIsSet = false;
    m_Is_available = true;
    m_Is_availableIsSet = false;
    m_Id = "";
    m_Mileage = 0.0;
    m_Last_service_dateIsSet = false;
    m_Doors = 0;
    m_Trunk_capacity = 0.0;
    m_Sunroof = false;
    m_SunroofIsSet = false;
    m_Parking_sensors = false;
    m_Parking_sensorsIsSet = false;
    
}

void CarResponseV2::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool CarResponseV2::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool CarResponseV2::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "CarResponseV2" : pathPrefix;

                         
    
    /* Vin */ {
        const std::string& value = m_Vin;
        const std::string currentValuePath = _pathPrefix + ".vin";
                
        
        if (value.length() < 17)
        {
            success = false;
            msg << currentValuePath << ": must be at least 17 characters long;";
        }
        if (value.length() > 17)
        {
            success = false;
            msg << currentValuePath << ": must be at most 17 characters long;";
        }

    }
                         
    
    /* Mileage */ {
        const double& value = m_Mileage;
        const std::string currentValuePath = _pathPrefix + ".mileage";
                
        
        if (value < 0.0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0.0;";
        }

    }
             
    
    /* Doors */ {
        const int32_t& value = m_Doors;
        const std::string currentValuePath = _pathPrefix + ".doors";
                
        
        if (value < 2)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 2;";
        }
        if (value > 5)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 5;";
        }

    }
         
    
    /* Trunk_capacity */ {
        const double& value = m_Trunk_capacity;
        const std::string currentValuePath = _pathPrefix + ".trunkCapacity";
                
        
        if (value < 0.0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0.0;";
        }
        if (value > 100.0)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 100.0;";
        }

    }
                    
    return success;
}

bool CarResponseV2::operator==(const CarResponseV2& rhs) const
{
    return
    
    
    (getMake() == rhs.getMake())
     &&
    
    (getModel() == rhs.getModel())
     &&
    
    (getYear() == rhs.getYear())
     &&
    
    (getColor() == rhs.getColor())
     &&
    
    (getVin() == rhs.getVin())
     &&
    
    (getRegistrationNumber() == rhs.getRegistrationNumber())
     &&
    
    
    ((!insuranceExpiryIsSet() && !rhs.insuranceExpiryIsSet()) || (insuranceExpiryIsSet() && rhs.insuranceExpiryIsSet() && getInsuranceExpiry() == rhs.getInsuranceExpiry())) &&
    
    
    ((!isAvailableIsSet() && !rhs.isAvailableIsSet()) || (isAvailableIsSet() && rhs.isAvailableIsSet() && isIsAvailable() == rhs.isIsAvailable())) &&
    
    (getId() == rhs.getId())
     &&
    
    (getMileage() == rhs.getMileage())
     &&
    
    
    ((!lastServiceDateIsSet() && !rhs.lastServiceDateIsSet()) || (lastServiceDateIsSet() && rhs.lastServiceDateIsSet() && getLastServiceDate() == rhs.getLastServiceDate())) &&
    
    (getDoors() == rhs.getDoors())
     &&
    
    (getTrunkCapacity() == rhs.getTrunkCapacity())
     &&
    
    (getFuelType() == rhs.getFuelType())
     &&
    
    (getTransmission() == rhs.getTransmission())
     &&
    
    
    ((!sunroofIsSet() && !rhs.sunroofIsSet()) || (sunroofIsSet() && rhs.sunroofIsSet() && isSunroof() == rhs.isSunroof())) &&
    
    
    ((!parkingSensorsIsSet() && !rhs.parkingSensorsIsSet()) || (parkingSensorsIsSet() && rhs.parkingSensorsIsSet() && isParkingSensors() == rhs.isParkingSensors()))
    
    ;
}

bool CarResponseV2::operator!=(const CarResponseV2& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const CarResponseV2& o)
{
    j = nlohmann::json::object();
    j["make"] = o.m_Make;
    j["model"] = o.m_Model;
    j["year"] = o.m_Year;
    j["color"] = o.m_Color;
    j["vin"] = o.m_Vin;
    j["registration_number"] = o.m_Registration_number;
    if(o.insuranceExpiryIsSet())
        j["insurance_expiry"] = o.m_Insurance_expiry;
    if(o.isAvailableIsSet())
        j["is_available"] = o.m_Is_available;
    j["id"] = o.m_Id;
    j["mileage"] = o.m_Mileage;
    if(o.lastServiceDateIsSet())
        j["last_service_date"] = o.m_Last_service_date;
    j["doors"] = o.m_Doors;
    j["trunk_capacity"] = o.m_Trunk_capacity;
    j["fuel_type"] = o.m_Fuel_type;
    j["transmission"] = o.m_Transmission;
    if(o.sunroofIsSet())
        j["sunroof"] = o.m_Sunroof;
    if(o.parkingSensorsIsSet())
        j["parking_sensors"] = o.m_Parking_sensors;
    
}

void from_json(const nlohmann::json& j, CarResponseV2& o)
{
    j.at("make").get_to(o.m_Make);
    j.at("model").get_to(o.m_Model);
    j.at("year").get_to(o.m_Year);
    j.at("color").get_to(o.m_Color);
    j.at("vin").get_to(o.m_Vin);
    j.at("registration_number").get_to(o.m_Registration_number);
    if(j.find("insurance_expiry") != j.end())
    {
        j.at("insurance_expiry").get_to(o.m_Insurance_expiry);
        o.m_Insurance_expiryIsSet = true;
    } 
    if(j.find("is_available") != j.end())
    {
        j.at("is_available").get_to(o.m_Is_available);
        o.m_Is_availableIsSet = true;
    } 
    j.at("id").get_to(o.m_Id);
    j.at("mileage").get_to(o.m_Mileage);
    if(j.find("last_service_date") != j.end())
    {
        j.at("last_service_date").get_to(o.m_Last_service_date);
        o.m_Last_service_dateIsSet = true;
    } 
    j.at("doors").get_to(o.m_Doors);
    j.at("trunk_capacity").get_to(o.m_Trunk_capacity);
    j.at("fuel_type").get_to(o.m_Fuel_type);
    j.at("transmission").get_to(o.m_Transmission);
    if(j.find("sunroof") != j.end())
    {
        j.at("sunroof").get_to(o.m_Sunroof);
        o.m_SunroofIsSet = true;
    } 
    if(j.find("parking_sensors") != j.end())
    {
        j.at("parking_sensors").get_to(o.m_Parking_sensors);
        o.m_Parking_sensorsIsSet = true;
    } 
    
}

std::string CarResponseV2::getMake() const
{
    return m_Make;
}
void CarResponseV2::setMake(std::string const& value)
{
    m_Make = value;
}
std::string CarResponseV2::getModel() const
{
    return m_Model;
}
void CarResponseV2::setModel(std::string const& value)
{
    m_Model = value;
}
int32_t CarResponseV2::getYear() const
{
    return m_Year;
}
void CarResponseV2::setYear(int32_t const value)
{
    m_Year = value;
}
std::string CarResponseV2::getColor() const
{
    return m_Color;
}
void CarResponseV2::setColor(std::string const& value)
{
    m_Color = value;
}
std::string CarResponseV2::getVin() const
{
    return m_Vin;
}
void CarResponseV2::setVin(std::string const& value)
{
    m_Vin = value;
}
std::string CarResponseV2::getRegistrationNumber() const
{
    return m_Registration_number;
}
void CarResponseV2::setRegistrationNumber(std::string const& value)
{
    m_Registration_number = value;
}
std::string CarResponseV2::getInsuranceExpiry() const
{
    return m_Insurance_expiry;
}
void CarResponseV2::setInsuranceExpiry(std::string const& value)
{
    m_Insurance_expiry = value;
    m_Insurance_expiryIsSet = true;
}
bool CarResponseV2::insuranceExpiryIsSet() const
{
    return m_Insurance_expiryIsSet;
}
void CarResponseV2::unsetInsurance_expiry()
{
    m_Insurance_expiryIsSet = false;
}
bool CarResponseV2::isIsAvailable() const
{
    return m_Is_available;
}
void CarResponseV2::setIsAvailable(bool const value)
{
    m_Is_available = value;
    m_Is_availableIsSet = true;
}
bool CarResponseV2::isAvailableIsSet() const
{
    return m_Is_availableIsSet;
}
void CarResponseV2::unsetIs_available()
{
    m_Is_availableIsSet = false;
}
std::string CarResponseV2::getId() const
{
    return m_Id;
}
void CarResponseV2::setId(std::string const& value)
{
    m_Id = value;
}
double CarResponseV2::getMileage() const
{
    return m_Mileage;
}
void CarResponseV2::setMileage(double const value)
{
    m_Mileage = value;
}
std::string CarResponseV2::getLastServiceDate() const
{
    return m_Last_service_date;
}
void CarResponseV2::setLastServiceDate(std::string const& value)
{
    m_Last_service_date = value;
    m_Last_service_dateIsSet = true;
}
bool CarResponseV2::lastServiceDateIsSet() const
{
    return m_Last_service_dateIsSet;
}
void CarResponseV2::unsetLast_service_date()
{
    m_Last_service_dateIsSet = false;
}
int32_t CarResponseV2::getDoors() const
{
    return m_Doors;
}
void CarResponseV2::setDoors(int32_t const value)
{
    m_Doors = value;
}
double CarResponseV2::getTrunkCapacity() const
{
    return m_Trunk_capacity;
}
void CarResponseV2::setTrunkCapacity(double const value)
{
    m_Trunk_capacity = value;
}
org::openapitools::server::model::FuelType CarResponseV2::getFuelType() const
{
    return m_Fuel_type;
}
void CarResponseV2::setFuelType(org::openapitools::server::model::FuelType const& value)
{
    m_Fuel_type = value;
}
org::openapitools::server::model::TransmissionType CarResponseV2::getTransmission() const
{
    return m_Transmission;
}
void CarResponseV2::setTransmission(org::openapitools::server::model::TransmissionType const& value)
{
    m_Transmission = value;
}
bool CarResponseV2::isSunroof() const
{
    return m_Sunroof;
}
void CarResponseV2::setSunroof(bool const value)
{
    m_Sunroof = value;
    m_SunroofIsSet = true;
}
bool CarResponseV2::sunroofIsSet() const
{
    return m_SunroofIsSet;
}
void CarResponseV2::unsetSunroof()
{
    m_SunroofIsSet = false;
}
bool CarResponseV2::isParkingSensors() const
{
    return m_Parking_sensors;
}
void CarResponseV2::setParkingSensors(bool const value)
{
    m_Parking_sensors = value;
    m_Parking_sensorsIsSet = true;
}
bool CarResponseV2::parkingSensorsIsSet() const
{
    return m_Parking_sensorsIsSet;
}
void CarResponseV2::unsetParking_sensors()
{
    m_Parking_sensorsIsSet = false;
}


} // namespace org::openapitools::server::model

