/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * FuelType.h
 *
 * 
 */

#ifndef FuelType_H_
#define FuelType_H_


#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  FuelType
{
public:
    FuelType();
    virtual ~FuelType() = default;

    enum class eFuelType {
    // To have a valid default value.
    // Avoiding name clashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    GASOLINE, 
    DIESEL, 
    ELECTRIC, 
    HYBRID
    };

    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const FuelType& rhs) const;
    bool operator!=(const FuelType& rhs) const;

    /////////////////////////////////////////////
    /// FuelType members

    FuelType::eFuelType getValue() const;
    void setValue(FuelType::eFuelType value);
    
    friend  void to_json(nlohmann::json& j, const FuelType& o);
    friend  void from_json(const nlohmann::json& j, FuelType& o);
protected:
    FuelType::eFuelType m_value = FuelType::eFuelType::INVALID_VALUE_OPENAPI_GENERATED;
};

} // namespace org::openapitools::server::model

#endif /* FuelType_H_ */
