/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "FuelType.h"
#include "Helpers.h"
#include <stdexcept>
#include <sstream>

namespace org::openapitools::server::model
{

FuelType::FuelType()
{
    
}

void FuelType::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool FuelType::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool FuelType::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "FuelType" : pathPrefix;

    
    if (m_value == FuelType::eFuelType::INVALID_VALUE_OPENAPI_GENERATED)
    {
        success = false;
        msg << _pathPrefix << ": has no value;";
    }

    return success;
}

bool FuelType::operator==(const FuelType& rhs) const
{
    return
    getValue() == rhs.getValue()
    
    ;
}

bool FuelType::operator!=(const FuelType& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const FuelType& o)
{
    j = nlohmann::json::object();
    
    switch (o.getValue())
    {
        case FuelType::eFuelType::INVALID_VALUE_OPENAPI_GENERATED:
            j = "INVALID_VALUE_OPENAPI_GENERATED";
            break;
        case FuelType::eFuelType::GASOLINE:
            j = "gasoline";
            break;
        case FuelType::eFuelType::DIESEL:
            j = "diesel";
            break;
        case FuelType::eFuelType::ELECTRIC:
            j = "electric";
            break;
        case FuelType::eFuelType::HYBRID:
            j = "hybrid";
            break;
    }
}

void from_json(const nlohmann::json& j, FuelType& o)
{
    
    auto s = j.get<std::string>();
    if (s == "gasoline") {
     o.setValue(FuelType::eFuelType::GASOLINE);
    } 
    else if (s == "diesel") {
     o.setValue(FuelType::eFuelType::DIESEL);
    } 
    else if (s == "electric") {
     o.setValue(FuelType::eFuelType::ELECTRIC);
    } 
    else if (s == "hybrid") {
     o.setValue(FuelType::eFuelType::HYBRID);
    }  else {
     std::stringstream ss;
     ss << "Unexpected value " << s << " in json"
        << " cannot be converted to enum of type"
        << " FuelType::eFuelType";
     throw std::invalid_argument(ss.str());
    } 

}

FuelType::eFuelType FuelType::getValue() const
{
    return m_value;
}
void FuelType::setValue(FuelType::eFuelType value)
{
    m_value = value;
}

} // namespace org::openapitools::server::model

