/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * HTTPValidationError.h
 *
 * 
 */

#ifndef HTTPValidationError_H_
#define HTTPValidationError_H_


#include "ValidationError.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  HTTPValidationError
{
public:
    HTTPValidationError();
    virtual ~HTTPValidationError() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const HTTPValidationError& rhs) const;
    bool operator!=(const HTTPValidationError& rhs) const;

    /////////////////////////////////////////////
    /// HTTPValidationError members

    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::ValidationError> getDetail() const;
    void setDetail(std::vector<org::openapitools::server::model::ValidationError> const& value);
    bool detailIsSet() const;
    void unsetDetail();

    friend  void to_json(nlohmann::json& j, const HTTPValidationError& o);
    friend  void from_json(const nlohmann::json& j, HTTPValidationError& o);
protected:
    std::vector<org::openapitools::server::model::ValidationError> m_Detail;
    bool m_DetailIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* HTTPValidationError_H_ */
