/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * TransmissionType.h
 *
 * 
 */

#ifndef TransmissionType_H_
#define TransmissionType_H_


#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  TransmissionType
{
public:
    TransmissionType();
    virtual ~TransmissionType() = default;

    enum class eTransmissionType {
    // To have a valid default value.
    // Avoiding name clashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    MANUAL, 
    AUTOMATIC, 
    CVT
    };

    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const TransmissionType& rhs) const;
    bool operator!=(const TransmissionType& rhs) const;

    /////////////////////////////////////////////
    /// TransmissionType members

    TransmissionType::eTransmissionType getValue() const;
    void setValue(TransmissionType::eTransmissionType value);
    
    friend  void to_json(nlohmann::json& j, const TransmissionType& o);
    friend  void from_json(const nlohmann::json& j, TransmissionType& o);
protected:
    TransmissionType::eTransmissionType m_value = TransmissionType::eTransmissionType::INVALID_VALUE_OPENAPI_GENERATED;
};

} // namespace org::openapitools::server::model

#endif /* TransmissionType_H_ */
