/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "TransmissionType.h"
#include "Helpers.h"
#include <stdexcept>
#include <sstream>

namespace org::openapitools::server::model
{

TransmissionType::TransmissionType()
{
    
}

void TransmissionType::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool TransmissionType::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool TransmissionType::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "TransmissionType" : pathPrefix;

    
    if (m_value == TransmissionType::eTransmissionType::INVALID_VALUE_OPENAPI_GENERATED)
    {
        success = false;
        msg << _pathPrefix << ": has no value;";
    }

    return success;
}

bool TransmissionType::operator==(const TransmissionType& rhs) const
{
    return
    getValue() == rhs.getValue()
    
    ;
}

bool TransmissionType::operator!=(const TransmissionType& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const TransmissionType& o)
{
    j = nlohmann::json::object();
    
    switch (o.getValue())
    {
        case TransmissionType::eTransmissionType::INVALID_VALUE_OPENAPI_GENERATED:
            j = "INVALID_VALUE_OPENAPI_GENERATED";
            break;
        case TransmissionType::eTransmissionType::MANUAL:
            j = "manual";
            break;
        case TransmissionType::eTransmissionType::AUTOMATIC:
            j = "automatic";
            break;
        case TransmissionType::eTransmissionType::CVT:
            j = "cvt";
            break;
    }
}

void from_json(const nlohmann::json& j, TransmissionType& o)
{
    
    auto s = j.get<std::string>();
    if (s == "manual") {
     o.setValue(TransmissionType::eTransmissionType::MANUAL);
    } 
    else if (s == "automatic") {
     o.setValue(TransmissionType::eTransmissionType::AUTOMATIC);
    } 
    else if (s == "cvt") {
     o.setValue(TransmissionType::eTransmissionType::CVT);
    }  else {
     std::stringstream ss;
     ss << "Unexpected value " << s << " in json"
        << " cannot be converted to enum of type"
        << " TransmissionType::eTransmissionType";
     throw std::invalid_argument(ss.str());
    } 

}

TransmissionType::eTransmissionType TransmissionType::getValue() const
{
    return m_value;
}
void TransmissionType::setValue(TransmissionType::eTransmissionType value)
{
    m_value = value;
}

} // namespace org::openapitools::server::model

