/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * TruckCreateV2.h
 *
 * Schema for creating a truck (V2).
 */

#ifndef TruckCreateV2_H_
#define TruckCreateV2_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Schema for creating a truck (V2).
/// </summary>
class  TruckCreateV2
{
public:
    TruckCreateV2();
    virtual ~TruckCreateV2() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const TruckCreateV2& rhs) const;
    bool operator!=(const TruckCreateV2& rhs) const;

    /////////////////////////////////////////////
    /// TruckCreateV2 members

    /// <summary>
    /// Make of the vehicle
    /// </summary>
    std::string getMake() const;
    void setMake(std::string const& value);
    /// <summary>
    /// Model of the vehicle
    /// </summary>
    std::string getModel() const;
    void setModel(std::string const& value);
    /// <summary>
    /// Year of manufacture
    /// </summary>
    int32_t getYear() const;
    void setYear(int32_t const value);
    /// <summary>
    /// Color of the vehicle
    /// </summary>
    std::string getColor() const;
    void setColor(std::string const& value);
    /// <summary>
    /// Vehicle Identification Number (VIN)
    /// </summary>
    std::string getVin() const;
    void setVin(std::string const& value);
    /// <summary>
    /// Vehicle registration number
    /// </summary>
    std::string getRegistrationNumber() const;
    void setRegistrationNumber(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getInsuranceExpiry() const;
    void setInsuranceExpiry(std::string const& value);
    bool insuranceExpiryIsSet() const;
    void unsetInsurance_expiry();
    /// <summary>
    /// Whether the vehicle is available for use
    /// </summary>
    bool isIsAvailable() const;
    void setIsAvailable(bool const value);
    bool isAvailableIsSet() const;
    void unsetIs_available();
    /// <summary>
    /// Length of the truck bed in feet
    /// </summary>
    double getBedLength() const;
    void setBedLength(double const value);
    /// <summary>
    /// Towing capacity in pounds
    /// </summary>
    double getTowingCapacity() const;
    void setTowingCapacity(double const value);
    /// <summary>
    /// Maximum payload capacity in pounds
    /// </summary>
    double getPayloadCapacity() const;
    void setPayloadCapacity(double const value);
    /// <summary>
    /// Engine size in liters
    /// </summary>
    double getEngineSize() const;
    void setEngineSize(double const value);
    /// <summary>
    /// Whether the truck has four-wheel drive
    /// </summary>
    bool isFourWheelDrive() const;
    void setFourWheelDrive(bool const value);
    bool fourWheelDriveIsSet() const;
    void unsetFour_wheel_drive();
    /// <summary>
    /// Whether the truck has a bed liner
    /// </summary>
    bool isBedLiner() const;
    void setBedLiner(bool const value);
    bool bedLinerIsSet() const;
    void unsetBed_liner();

    friend  void to_json(nlohmann::json& j, const TruckCreateV2& o);
    friend  void from_json(const nlohmann::json& j, TruckCreateV2& o);
protected:
    std::string m_Make;

    std::string m_Model;

    int32_t m_Year;

    std::string m_Color;

    std::string m_Vin;

    std::string m_Registration_number;

    std::string m_Insurance_expiry;
    bool m_Insurance_expiryIsSet;
    bool m_Is_available;
    bool m_Is_availableIsSet;
    double m_Bed_length;

    double m_Towing_capacity;

    double m_Payload_capacity;

    double m_Engine_size;

    bool m_Four_wheel_drive;
    bool m_Four_wheel_driveIsSet;
    bool m_Bed_liner;
    bool m_Bed_linerIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* TruckCreateV2_H_ */
