/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * TruckResponseV1.h
 *
 * Schema for truck responses, including ID (V1).
 */

#ifndef TruckResponseV1_H_
#define TruckResponseV1_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Schema for truck responses, including ID (V1).
/// </summary>
class  TruckResponseV1
{
public:
    TruckResponseV1();
    virtual ~TruckResponseV1() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const TruckResponseV1& rhs) const;
    bool operator!=(const TruckResponseV1& rhs) const;

    /////////////////////////////////////////////
    /// TruckResponseV1 members

    /// <summary>
    /// Make of the vehicle
    /// </summary>
    std::string getMake() const;
    void setMake(std::string const& value);
    /// <summary>
    /// Model of the vehicle
    /// </summary>
    std::string getModel() const;
    void setModel(std::string const& value);
    /// <summary>
    /// Year of manufacture
    /// </summary>
    int32_t getYear() const;
    void setYear(int32_t const value);
    /// <summary>
    /// Color of the vehicle
    /// </summary>
    std::string getColor() const;
    void setColor(std::string const& value);
    /// <summary>
    /// Vehicle Identification Number (VIN)
    /// </summary>
    std::string getVin() const;
    void setVin(std::string const& value);
    /// <summary>
    /// Current mileage of the vehicle
    /// </summary>
    double getMileage() const;
    void setMileage(double const value);
    /// <summary>
    /// 
    /// </summary>
    std::string getLastServiceDate() const;
    void setLastServiceDate(std::string const& value);
    bool lastServiceDateIsSet() const;
    void unsetLast_service_date();
    /// <summary>
    /// Unique identifier for the vehicle
    /// </summary>
    std::string getId() const;
    void setId(std::string const& value);
    /// <summary>
    /// Length of the truck bed in feet
    /// </summary>
    double getBedLength() const;
    void setBedLength(double const value);
    /// <summary>
    /// Towing capacity in pounds
    /// </summary>
    double getTowingCapacity() const;
    void setTowingCapacity(double const value);
    /// <summary>
    /// Maximum payload capacity in pounds
    /// </summary>
    double getPayloadCapacity() const;
    void setPayloadCapacity(double const value);
    /// <summary>
    /// Engine size in liters
    /// </summary>
    double getEngineSize() const;
    void setEngineSize(double const value);

    friend  void to_json(nlohmann::json& j, const TruckResponseV1& o);
    friend  void from_json(const nlohmann::json& j, TruckResponseV1& o);
protected:
    std::string m_Make;

    std::string m_Model;

    int32_t m_Year;

    std::string m_Color;

    std::string m_Vin;

    double m_Mileage;

    std::string m_Last_service_date;
    bool m_Last_service_dateIsSet;
    std::string m_Id;

    double m_Bed_length;

    double m_Towing_capacity;

    double m_Payload_capacity;

    double m_Engine_size;

    
};

} // namespace org::openapitools::server::model

#endif /* TruckResponseV1_H_ */
