/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "TruckResponseV2.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

TruckResponseV2::TruckResponseV2()
{
    m_Make = "";
    m_Model = "";
    m_Year = 0;
    m_Color = "";
    m_Vin = "";
    m_Registration_number = "";
    m_Insurance_expiryIsSet = false;
    m_Is_available = true;
    m_Is_availableIsSet = false;
    m_Id = "";
    m_Mileage = 0.0;
    m_Last_service_dateIsSet = false;
    m_Bed_length = 0.0;
    m_Towing_capacity = 0.0;
    m_Payload_capacity = 0.0;
    m_Engine_size = 0.0;
    m_Four_wheel_drive = false;
    m_Four_wheel_driveIsSet = false;
    m_Bed_liner = false;
    m_Bed_linerIsSet = false;
    
}

void TruckResponseV2::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool TruckResponseV2::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool TruckResponseV2::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "TruckResponseV2" : pathPrefix;

                         
    
    /* Vin */ {
        const std::string& value = m_Vin;
        const std::string currentValuePath = _pathPrefix + ".vin";
                
        
        if (value.length() < 17)
        {
            success = false;
            msg << currentValuePath << ": must be at least 17 characters long;";
        }
        if (value.length() > 17)
        {
            success = false;
            msg << currentValuePath << ": must be at most 17 characters long;";
        }

    }
                         
    
    /* Mileage */ {
        const double& value = m_Mileage;
        const std::string currentValuePath = _pathPrefix + ".mileage";
                
        
        if (value < 0.0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0.0;";
        }

    }
                 
    
    /* Towing_capacity */ {
        const double& value = m_Towing_capacity;
        const std::string currentValuePath = _pathPrefix + ".towingCapacity";
                
        
        if (value < 0.0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0.0;";
        }
        if (value > 100000.0)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 100000.0;";
        }

    }
                    
    return success;
}

bool TruckResponseV2::operator==(const TruckResponseV2& rhs) const
{
    return
    
    
    (getMake() == rhs.getMake())
     &&
    
    (getModel() == rhs.getModel())
     &&
    
    (getYear() == rhs.getYear())
     &&
    
    (getColor() == rhs.getColor())
     &&
    
    (getVin() == rhs.getVin())
     &&
    
    (getRegistrationNumber() == rhs.getRegistrationNumber())
     &&
    
    
    ((!insuranceExpiryIsSet() && !rhs.insuranceExpiryIsSet()) || (insuranceExpiryIsSet() && rhs.insuranceExpiryIsSet() && getInsuranceExpiry() == rhs.getInsuranceExpiry())) &&
    
    
    ((!isAvailableIsSet() && !rhs.isAvailableIsSet()) || (isAvailableIsSet() && rhs.isAvailableIsSet() && isIsAvailable() == rhs.isIsAvailable())) &&
    
    (getId() == rhs.getId())
     &&
    
    (getMileage() == rhs.getMileage())
     &&
    
    
    ((!lastServiceDateIsSet() && !rhs.lastServiceDateIsSet()) || (lastServiceDateIsSet() && rhs.lastServiceDateIsSet() && getLastServiceDate() == rhs.getLastServiceDate())) &&
    
    (getBedLength() == rhs.getBedLength())
     &&
    
    (getTowingCapacity() == rhs.getTowingCapacity())
     &&
    
    (getPayloadCapacity() == rhs.getPayloadCapacity())
     &&
    
    (getEngineSize() == rhs.getEngineSize())
     &&
    
    
    ((!fourWheelDriveIsSet() && !rhs.fourWheelDriveIsSet()) || (fourWheelDriveIsSet() && rhs.fourWheelDriveIsSet() && isFourWheelDrive() == rhs.isFourWheelDrive())) &&
    
    
    ((!bedLinerIsSet() && !rhs.bedLinerIsSet()) || (bedLinerIsSet() && rhs.bedLinerIsSet() && isBedLiner() == rhs.isBedLiner()))
    
    ;
}

bool TruckResponseV2::operator!=(const TruckResponseV2& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const TruckResponseV2& o)
{
    j = nlohmann::json::object();
    j["make"] = o.m_Make;
    j["model"] = o.m_Model;
    j["year"] = o.m_Year;
    j["color"] = o.m_Color;
    j["vin"] = o.m_Vin;
    j["registration_number"] = o.m_Registration_number;
    if(o.insuranceExpiryIsSet())
        j["insurance_expiry"] = o.m_Insurance_expiry;
    if(o.isAvailableIsSet())
        j["is_available"] = o.m_Is_available;
    j["id"] = o.m_Id;
    j["mileage"] = o.m_Mileage;
    if(o.lastServiceDateIsSet())
        j["last_service_date"] = o.m_Last_service_date;
    j["bed_length"] = o.m_Bed_length;
    j["towing_capacity"] = o.m_Towing_capacity;
    j["payload_capacity"] = o.m_Payload_capacity;
    j["engine_size"] = o.m_Engine_size;
    if(o.fourWheelDriveIsSet())
        j["four_wheel_drive"] = o.m_Four_wheel_drive;
    if(o.bedLinerIsSet())
        j["bed_liner"] = o.m_Bed_liner;
    
}

void from_json(const nlohmann::json& j, TruckResponseV2& o)
{
    j.at("make").get_to(o.m_Make);
    j.at("model").get_to(o.m_Model);
    j.at("year").get_to(o.m_Year);
    j.at("color").get_to(o.m_Color);
    j.at("vin").get_to(o.m_Vin);
    j.at("registration_number").get_to(o.m_Registration_number);
    if(j.find("insurance_expiry") != j.end())
    {
        j.at("insurance_expiry").get_to(o.m_Insurance_expiry);
        o.m_Insurance_expiryIsSet = true;
    } 
    if(j.find("is_available") != j.end())
    {
        j.at("is_available").get_to(o.m_Is_available);
        o.m_Is_availableIsSet = true;
    } 
    j.at("id").get_to(o.m_Id);
    j.at("mileage").get_to(o.m_Mileage);
    if(j.find("last_service_date") != j.end())
    {
        j.at("last_service_date").get_to(o.m_Last_service_date);
        o.m_Last_service_dateIsSet = true;
    } 
    j.at("bed_length").get_to(o.m_Bed_length);
    j.at("towing_capacity").get_to(o.m_Towing_capacity);
    j.at("payload_capacity").get_to(o.m_Payload_capacity);
    j.at("engine_size").get_to(o.m_Engine_size);
    if(j.find("four_wheel_drive") != j.end())
    {
        j.at("four_wheel_drive").get_to(o.m_Four_wheel_drive);
        o.m_Four_wheel_driveIsSet = true;
    } 
    if(j.find("bed_liner") != j.end())
    {
        j.at("bed_liner").get_to(o.m_Bed_liner);
        o.m_Bed_linerIsSet = true;
    } 
    
}

std::string TruckResponseV2::getMake() const
{
    return m_Make;
}
void TruckResponseV2::setMake(std::string const& value)
{
    m_Make = value;
}
std::string TruckResponseV2::getModel() const
{
    return m_Model;
}
void TruckResponseV2::setModel(std::string const& value)
{
    m_Model = value;
}
int32_t TruckResponseV2::getYear() const
{
    return m_Year;
}
void TruckResponseV2::setYear(int32_t const value)
{
    m_Year = value;
}
std::string TruckResponseV2::getColor() const
{
    return m_Color;
}
void TruckResponseV2::setColor(std::string const& value)
{
    m_Color = value;
}
std::string TruckResponseV2::getVin() const
{
    return m_Vin;
}
void TruckResponseV2::setVin(std::string const& value)
{
    m_Vin = value;
}
std::string TruckResponseV2::getRegistrationNumber() const
{
    return m_Registration_number;
}
void TruckResponseV2::setRegistrationNumber(std::string const& value)
{
    m_Registration_number = value;
}
std::string TruckResponseV2::getInsuranceExpiry() const
{
    return m_Insurance_expiry;
}
void TruckResponseV2::setInsuranceExpiry(std::string const& value)
{
    m_Insurance_expiry = value;
    m_Insurance_expiryIsSet = true;
}
bool TruckResponseV2::insuranceExpiryIsSet() const
{
    return m_Insurance_expiryIsSet;
}
void TruckResponseV2::unsetInsurance_expiry()
{
    m_Insurance_expiryIsSet = false;
}
bool TruckResponseV2::isIsAvailable() const
{
    return m_Is_available;
}
void TruckResponseV2::setIsAvailable(bool const value)
{
    m_Is_available = value;
    m_Is_availableIsSet = true;
}
bool TruckResponseV2::isAvailableIsSet() const
{
    return m_Is_availableIsSet;
}
void TruckResponseV2::unsetIs_available()
{
    m_Is_availableIsSet = false;
}
std::string TruckResponseV2::getId() const
{
    return m_Id;
}
void TruckResponseV2::setId(std::string const& value)
{
    m_Id = value;
}
double TruckResponseV2::getMileage() const
{
    return m_Mileage;
}
void TruckResponseV2::setMileage(double const value)
{
    m_Mileage = value;
}
std::string TruckResponseV2::getLastServiceDate() const
{
    return m_Last_service_date;
}
void TruckResponseV2::setLastServiceDate(std::string const& value)
{
    m_Last_service_date = value;
    m_Last_service_dateIsSet = true;
}
bool TruckResponseV2::lastServiceDateIsSet() const
{
    return m_Last_service_dateIsSet;
}
void TruckResponseV2::unsetLast_service_date()
{
    m_Last_service_dateIsSet = false;
}
double TruckResponseV2::getBedLength() const
{
    return m_Bed_length;
}
void TruckResponseV2::setBedLength(double const value)
{
    m_Bed_length = value;
}
double TruckResponseV2::getTowingCapacity() const
{
    return m_Towing_capacity;
}
void TruckResponseV2::setTowingCapacity(double const value)
{
    m_Towing_capacity = value;
}
double TruckResponseV2::getPayloadCapacity() const
{
    return m_Payload_capacity;
}
void TruckResponseV2::setPayloadCapacity(double const value)
{
    m_Payload_capacity = value;
}
double TruckResponseV2::getEngineSize() const
{
    return m_Engine_size;
}
void TruckResponseV2::setEngineSize(double const value)
{
    m_Engine_size = value;
}
bool TruckResponseV2::isFourWheelDrive() const
{
    return m_Four_wheel_drive;
}
void TruckResponseV2::setFourWheelDrive(bool const value)
{
    m_Four_wheel_drive = value;
    m_Four_wheel_driveIsSet = true;
}
bool TruckResponseV2::fourWheelDriveIsSet() const
{
    return m_Four_wheel_driveIsSet;
}
void TruckResponseV2::unsetFour_wheel_drive()
{
    m_Four_wheel_driveIsSet = false;
}
bool TruckResponseV2::isBedLiner() const
{
    return m_Bed_liner;
}
void TruckResponseV2::setBedLiner(bool const value)
{
    m_Bed_liner = value;
    m_Bed_linerIsSet = true;
}
bool TruckResponseV2::bedLinerIsSet() const
{
    return m_Bed_linerIsSet;
}
void TruckResponseV2::unsetBed_liner()
{
    m_Bed_linerIsSet = false;
}


} // namespace org::openapitools::server::model

