/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "TruckResponseV1.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

TruckResponseV1::TruckResponseV1()
{
    m_Make = "";
    m_Model = "";
    m_Year = 0;
    m_Color = "";
    m_Vin = "";
    m_Mileage = 0.0;
    m_Last_service_dateIsSet = false;
    m_Id = "";
    m_Bed_length = 0.0;
    m_Towing_capacity = 0.0;
    m_Payload_capacity = 0.0;
    m_Engine_size = 0.0;
    
}

void TruckResponseV1::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool TruckResponseV1::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool TruckResponseV1::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "TruckResponseV1" : pathPrefix;

                         
    
    /* Vin */ {
        const std::string& value = m_Vin;
        const std::string currentValuePath = _pathPrefix + ".vin";
                
        
        if (value.length() < 17)
        {
            success = false;
            msg << currentValuePath << ": must be at least 17 characters long;";
        }
        if (value.length() > 17)
        {
            success = false;
            msg << currentValuePath << ": must be at most 17 characters long;";
        }

    }
         
    
    /* Mileage */ {
        const double& value = m_Mileage;
        const std::string currentValuePath = _pathPrefix + ".mileage";
                
        
        if (value < 0.0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0.0;";
        }

    }
                     
    
    /* Towing_capacity */ {
        const double& value = m_Towing_capacity;
        const std::string currentValuePath = _pathPrefix + ".towingCapacity";
                
        
        if (value < 0.0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0.0;";
        }
        if (value > 100000.0)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 100000.0;";
        }

    }
            
    return success;
}

bool TruckResponseV1::operator==(const TruckResponseV1& rhs) const
{
    return
    
    
    (getMake() == rhs.getMake())
     &&
    
    (getModel() == rhs.getModel())
     &&
    
    (getYear() == rhs.getYear())
     &&
    
    (getColor() == rhs.getColor())
     &&
    
    (getVin() == rhs.getVin())
     &&
    
    (getMileage() == rhs.getMileage())
     &&
    
    
    ((!lastServiceDateIsSet() && !rhs.lastServiceDateIsSet()) || (lastServiceDateIsSet() && rhs.lastServiceDateIsSet() && getLastServiceDate() == rhs.getLastServiceDate())) &&
    
    (getId() == rhs.getId())
     &&
    
    (getBedLength() == rhs.getBedLength())
     &&
    
    (getTowingCapacity() == rhs.getTowingCapacity())
     &&
    
    (getPayloadCapacity() == rhs.getPayloadCapacity())
     &&
    
    (getEngineSize() == rhs.getEngineSize())
    
    
    ;
}

bool TruckResponseV1::operator!=(const TruckResponseV1& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const TruckResponseV1& o)
{
    j = nlohmann::json::object();
    j["make"] = o.m_Make;
    j["model"] = o.m_Model;
    j["year"] = o.m_Year;
    j["color"] = o.m_Color;
    j["vin"] = o.m_Vin;
    j["mileage"] = o.m_Mileage;
    if(o.lastServiceDateIsSet())
        j["last_service_date"] = o.m_Last_service_date;
    j["id"] = o.m_Id;
    j["bed_length"] = o.m_Bed_length;
    j["towing_capacity"] = o.m_Towing_capacity;
    j["payload_capacity"] = o.m_Payload_capacity;
    j["engine_size"] = o.m_Engine_size;
    
}

void from_json(const nlohmann::json& j, TruckResponseV1& o)
{
    j.at("make").get_to(o.m_Make);
    j.at("model").get_to(o.m_Model);
    j.at("year").get_to(o.m_Year);
    j.at("color").get_to(o.m_Color);
    j.at("vin").get_to(o.m_Vin);
    j.at("mileage").get_to(o.m_Mileage);
    if(j.find("last_service_date") != j.end())
    {
        j.at("last_service_date").get_to(o.m_Last_service_date);
        o.m_Last_service_dateIsSet = true;
    } 
    j.at("id").get_to(o.m_Id);
    j.at("bed_length").get_to(o.m_Bed_length);
    j.at("towing_capacity").get_to(o.m_Towing_capacity);
    j.at("payload_capacity").get_to(o.m_Payload_capacity);
    j.at("engine_size").get_to(o.m_Engine_size);
    
}

std::string TruckResponseV1::getMake() const
{
    return m_Make;
}
void TruckResponseV1::setMake(std::string const& value)
{
    m_Make = value;
}
std::string TruckResponseV1::getModel() const
{
    return m_Model;
}
void TruckResponseV1::setModel(std::string const& value)
{
    m_Model = value;
}
int32_t TruckResponseV1::getYear() const
{
    return m_Year;
}
void TruckResponseV1::setYear(int32_t const value)
{
    m_Year = value;
}
std::string TruckResponseV1::getColor() const
{
    return m_Color;
}
void TruckResponseV1::setColor(std::string const& value)
{
    m_Color = value;
}
std::string TruckResponseV1::getVin() const
{
    return m_Vin;
}
void TruckResponseV1::setVin(std::string const& value)
{
    m_Vin = value;
}
double TruckResponseV1::getMileage() const
{
    return m_Mileage;
}
void TruckResponseV1::setMileage(double const value)
{
    m_Mileage = value;
}
std::string TruckResponseV1::getLastServiceDate() const
{
    return m_Last_service_date;
}
void TruckResponseV1::setLastServiceDate(std::string const& value)
{
    m_Last_service_date = value;
    m_Last_service_dateIsSet = true;
}
bool TruckResponseV1::lastServiceDateIsSet() const
{
    return m_Last_service_dateIsSet;
}
void TruckResponseV1::unsetLast_service_date()
{
    m_Last_service_dateIsSet = false;
}
std::string TruckResponseV1::getId() const
{
    return m_Id;
}
void TruckResponseV1::setId(std::string const& value)
{
    m_Id = value;
}
double TruckResponseV1::getBedLength() const
{
    return m_Bed_length;
}
void TruckResponseV1::setBedLength(double const value)
{
    m_Bed_length = value;
}
double TruckResponseV1::getTowingCapacity() const
{
    return m_Towing_capacity;
}
void TruckResponseV1::setTowingCapacity(double const value)
{
    m_Towing_capacity = value;
}
double TruckResponseV1::getPayloadCapacity() const
{
    return m_Payload_capacity;
}
void TruckResponseV1::setPayloadCapacity(double const value)
{
    m_Payload_capacity = value;
}
double TruckResponseV1::getEngineSize() const
{
    return m_Engine_size;
}
void TruckResponseV1::setEngineSize(double const value)
{
    m_Engine_size = value;
}


} // namespace org::openapitools::server::model

