/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "ValidationError_loc_inner.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

ValidationError_loc_inner::ValidationError_loc_inner()
{
    
}

void ValidationError_loc_inner::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool ValidationError_loc_inner::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool ValidationError_loc_inner::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "ValidationError_loc_inner" : pathPrefix;

    
    return success;
}

bool ValidationError_loc_inner::operator==(const ValidationError_loc_inner& rhs) const
{
    return
    
    
    ;
}

bool ValidationError_loc_inner::operator!=(const ValidationError_loc_inner& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ValidationError_loc_inner& o)
{
    j = nlohmann::json::object();
    
}

void from_json(const nlohmann::json& j, ValidationError_loc_inner& o)
{
    
}



} // namespace org::openapitools::server::model

