/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ValidationError.h
 *
 * 
 */

#ifndef ValidationError_H_
#define ValidationError_H_


#include <string>
#include <vector>
#include "ValidationError_loc_inner.h"
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  ValidationError
{
public:
    ValidationError();
    virtual ~ValidationError() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const ValidationError& rhs) const;
    bool operator!=(const ValidationError& rhs) const;

    /////////////////////////////////////////////
    /// ValidationError members

    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::ValidationError_loc_inner> getLoc() const;
    void setLoc(std::vector<org::openapitools::server::model::ValidationError_loc_inner> const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getMsg() const;
    void setMsg(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getType() const;
    void setType(std::string const& value);

    friend  void to_json(nlohmann::json& j, const ValidationError& o);
    friend  void from_json(const nlohmann::json& j, ValidationError& o);
protected:
    std::vector<org::openapitools::server::model::ValidationError_loc_inner> m_Loc;

    std::string m_Msg;

    std::string m_Type;

    
};

} // namespace org::openapitools::server::model

#endif /* ValidationError_H_ */
