/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ValidationError_loc_inner.h
 *
 * 
 */

#ifndef ValidationError_loc_inner_H_
#define ValidationError_loc_inner_H_


#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  ValidationError_loc_inner
{
public:
    ValidationError_loc_inner();
    virtual ~ValidationError_loc_inner() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const ValidationError_loc_inner& rhs) const;
    bool operator!=(const ValidationError_loc_inner& rhs) const;

    /////////////////////////////////////////////
    /// ValidationError_loc_inner members


    friend  void to_json(nlohmann::json& j, const ValidationError_loc_inner& o);
    friend  void from_json(const nlohmann::json& j, ValidationError_loc_inner& o);
protected:
    
};

} // namespace org::openapitools::server::model

#endif /* ValidationError_loc_inner_H_ */
