/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Vehicle_1.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

Vehicle_1::Vehicle_1()
{
    m_Make = "";
    m_Model = "";
    m_Year = 0;
    m_Color = "";
    m_Vin = "";
    m_Registration_number = "";
    m_Insurance_expiryIsSet = false;
    m_Is_available = true;
    m_Is_availableIsSet = false;
    m_Doors = 0;
    m_Trunk_capacity = 0.0;
    m_Sunroof = false;
    m_SunroofIsSet = false;
    m_Parking_sensors = false;
    m_Parking_sensorsIsSet = false;
    m_Bed_length = 0.0;
    m_Towing_capacity = 0.0;
    m_Payload_capacity = 0.0;
    m_Engine_size = 0.0;
    m_Four_wheel_drive = false;
    m_Four_wheel_driveIsSet = false;
    m_Bed_liner = false;
    m_Bed_linerIsSet = false;
    
}

void Vehicle_1::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool Vehicle_1::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool Vehicle_1::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "Vehicle_1" : pathPrefix;

                         
    
    /* Vin */ {
        const std::string& value = m_Vin;
        const std::string currentValuePath = _pathPrefix + ".vin";
                
        
        if (value.length() < 17)
        {
            success = false;
            msg << currentValuePath << ": must be at least 17 characters long;";
        }
        if (value.length() > 17)
        {
            success = false;
            msg << currentValuePath << ": must be at most 17 characters long;";
        }

    }
                     
    
    /* Doors */ {
        const int32_t& value = m_Doors;
        const std::string currentValuePath = _pathPrefix + ".doors";
                
        
        if (value < 2)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 2;";
        }
        if (value > 5)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 5;";
        }

    }
         
    
    /* Trunk_capacity */ {
        const double& value = m_Trunk_capacity;
        const std::string currentValuePath = _pathPrefix + ".trunkCapacity";
                
        
        if (value < 0.0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0.0;";
        }
        if (value > 100.0)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 100.0;";
        }

    }
                             
    
    /* Towing_capacity */ {
        const double& value = m_Towing_capacity;
        const std::string currentValuePath = _pathPrefix + ".towingCapacity";
                
        
        if (value < 0.0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0.0;";
        }
        if (value > 100000.0)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 100000.0;";
        }

    }
                    
    return success;
}

bool Vehicle_1::operator==(const Vehicle_1& rhs) const
{
    return
    
    
    (getMake() == rhs.getMake())
     &&
    
    (getModel() == rhs.getModel())
     &&
    
    (getYear() == rhs.getYear())
     &&
    
    (getColor() == rhs.getColor())
     &&
    
    (getVin() == rhs.getVin())
     &&
    
    (getRegistrationNumber() == rhs.getRegistrationNumber())
     &&
    
    
    ((!insuranceExpiryIsSet() && !rhs.insuranceExpiryIsSet()) || (insuranceExpiryIsSet() && rhs.insuranceExpiryIsSet() && getInsuranceExpiry() == rhs.getInsuranceExpiry())) &&
    
    
    ((!isAvailableIsSet() && !rhs.isAvailableIsSet()) || (isAvailableIsSet() && rhs.isAvailableIsSet() && isIsAvailable() == rhs.isIsAvailable())) &&
    
    (getDoors() == rhs.getDoors())
     &&
    
    (getTrunkCapacity() == rhs.getTrunkCapacity())
     &&
    
    (getFuelType() == rhs.getFuelType())
     &&
    
    (getTransmission() == rhs.getTransmission())
     &&
    
    
    ((!sunroofIsSet() && !rhs.sunroofIsSet()) || (sunroofIsSet() && rhs.sunroofIsSet() && isSunroof() == rhs.isSunroof())) &&
    
    
    ((!parkingSensorsIsSet() && !rhs.parkingSensorsIsSet()) || (parkingSensorsIsSet() && rhs.parkingSensorsIsSet() && isParkingSensors() == rhs.isParkingSensors())) &&
    
    (getBedLength() == rhs.getBedLength())
     &&
    
    (getTowingCapacity() == rhs.getTowingCapacity())
     &&
    
    (getPayloadCapacity() == rhs.getPayloadCapacity())
     &&
    
    (getEngineSize() == rhs.getEngineSize())
     &&
    
    
    ((!fourWheelDriveIsSet() && !rhs.fourWheelDriveIsSet()) || (fourWheelDriveIsSet() && rhs.fourWheelDriveIsSet() && isFourWheelDrive() == rhs.isFourWheelDrive())) &&
    
    
    ((!bedLinerIsSet() && !rhs.bedLinerIsSet()) || (bedLinerIsSet() && rhs.bedLinerIsSet() && isBedLiner() == rhs.isBedLiner()))
    
    ;
}

bool Vehicle_1::operator!=(const Vehicle_1& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Vehicle_1& o)
{
    j = nlohmann::json::object();
    j["make"] = o.m_Make;
    j["model"] = o.m_Model;
    j["year"] = o.m_Year;
    j["color"] = o.m_Color;
    j["vin"] = o.m_Vin;
    j["registration_number"] = o.m_Registration_number;
    if(o.insuranceExpiryIsSet())
        j["insurance_expiry"] = o.m_Insurance_expiry;
    if(o.isAvailableIsSet())
        j["is_available"] = o.m_Is_available;
    j["doors"] = o.m_Doors;
    j["trunk_capacity"] = o.m_Trunk_capacity;
    j["fuel_type"] = o.m_Fuel_type;
    j["transmission"] = o.m_Transmission;
    if(o.sunroofIsSet())
        j["sunroof"] = o.m_Sunroof;
    if(o.parkingSensorsIsSet())
        j["parking_sensors"] = o.m_Parking_sensors;
    j["bed_length"] = o.m_Bed_length;
    j["towing_capacity"] = o.m_Towing_capacity;
    j["payload_capacity"] = o.m_Payload_capacity;
    j["engine_size"] = o.m_Engine_size;
    if(o.fourWheelDriveIsSet())
        j["four_wheel_drive"] = o.m_Four_wheel_drive;
    if(o.bedLinerIsSet())
        j["bed_liner"] = o.m_Bed_liner;
    
}

void from_json(const nlohmann::json& j, Vehicle_1& o)
{
    j.at("make").get_to(o.m_Make);
    j.at("model").get_to(o.m_Model);
    j.at("year").get_to(o.m_Year);
    j.at("color").get_to(o.m_Color);
    j.at("vin").get_to(o.m_Vin);
    j.at("registration_number").get_to(o.m_Registration_number);
    if(j.find("insurance_expiry") != j.end())
    {
        j.at("insurance_expiry").get_to(o.m_Insurance_expiry);
        o.m_Insurance_expiryIsSet = true;
    } 
    if(j.find("is_available") != j.end())
    {
        j.at("is_available").get_to(o.m_Is_available);
        o.m_Is_availableIsSet = true;
    } 
    j.at("doors").get_to(o.m_Doors);
    j.at("trunk_capacity").get_to(o.m_Trunk_capacity);
    j.at("fuel_type").get_to(o.m_Fuel_type);
    j.at("transmission").get_to(o.m_Transmission);
    if(j.find("sunroof") != j.end())
    {
        j.at("sunroof").get_to(o.m_Sunroof);
        o.m_SunroofIsSet = true;
    } 
    if(j.find("parking_sensors") != j.end())
    {
        j.at("parking_sensors").get_to(o.m_Parking_sensors);
        o.m_Parking_sensorsIsSet = true;
    } 
    j.at("bed_length").get_to(o.m_Bed_length);
    j.at("towing_capacity").get_to(o.m_Towing_capacity);
    j.at("payload_capacity").get_to(o.m_Payload_capacity);
    j.at("engine_size").get_to(o.m_Engine_size);
    if(j.find("four_wheel_drive") != j.end())
    {
        j.at("four_wheel_drive").get_to(o.m_Four_wheel_drive);
        o.m_Four_wheel_driveIsSet = true;
    } 
    if(j.find("bed_liner") != j.end())
    {
        j.at("bed_liner").get_to(o.m_Bed_liner);
        o.m_Bed_linerIsSet = true;
    } 
    
}

std::string Vehicle_1::getMake() const
{
    return m_Make;
}
void Vehicle_1::setMake(std::string const& value)
{
    m_Make = value;
}
std::string Vehicle_1::getModel() const
{
    return m_Model;
}
void Vehicle_1::setModel(std::string const& value)
{
    m_Model = value;
}
int32_t Vehicle_1::getYear() const
{
    return m_Year;
}
void Vehicle_1::setYear(int32_t const value)
{
    m_Year = value;
}
std::string Vehicle_1::getColor() const
{
    return m_Color;
}
void Vehicle_1::setColor(std::string const& value)
{
    m_Color = value;
}
std::string Vehicle_1::getVin() const
{
    return m_Vin;
}
void Vehicle_1::setVin(std::string const& value)
{
    m_Vin = value;
}
std::string Vehicle_1::getRegistrationNumber() const
{
    return m_Registration_number;
}
void Vehicle_1::setRegistrationNumber(std::string const& value)
{
    m_Registration_number = value;
}
std::string Vehicle_1::getInsuranceExpiry() const
{
    return m_Insurance_expiry;
}
void Vehicle_1::setInsuranceExpiry(std::string const& value)
{
    m_Insurance_expiry = value;
    m_Insurance_expiryIsSet = true;
}
bool Vehicle_1::insuranceExpiryIsSet() const
{
    return m_Insurance_expiryIsSet;
}
void Vehicle_1::unsetInsurance_expiry()
{
    m_Insurance_expiryIsSet = false;
}
bool Vehicle_1::isIsAvailable() const
{
    return m_Is_available;
}
void Vehicle_1::setIsAvailable(bool const value)
{
    m_Is_available = value;
    m_Is_availableIsSet = true;
}
bool Vehicle_1::isAvailableIsSet() const
{
    return m_Is_availableIsSet;
}
void Vehicle_1::unsetIs_available()
{
    m_Is_availableIsSet = false;
}
int32_t Vehicle_1::getDoors() const
{
    return m_Doors;
}
void Vehicle_1::setDoors(int32_t const value)
{
    m_Doors = value;
}
double Vehicle_1::getTrunkCapacity() const
{
    return m_Trunk_capacity;
}
void Vehicle_1::setTrunkCapacity(double const value)
{
    m_Trunk_capacity = value;
}
org::openapitools::server::model::FuelType Vehicle_1::getFuelType() const
{
    return m_Fuel_type;
}
void Vehicle_1::setFuelType(org::openapitools::server::model::FuelType const& value)
{
    m_Fuel_type = value;
}
org::openapitools::server::model::TransmissionType Vehicle_1::getTransmission() const
{
    return m_Transmission;
}
void Vehicle_1::setTransmission(org::openapitools::server::model::TransmissionType const& value)
{
    m_Transmission = value;
}
bool Vehicle_1::isSunroof() const
{
    return m_Sunroof;
}
void Vehicle_1::setSunroof(bool const value)
{
    m_Sunroof = value;
    m_SunroofIsSet = true;
}
bool Vehicle_1::sunroofIsSet() const
{
    return m_SunroofIsSet;
}
void Vehicle_1::unsetSunroof()
{
    m_SunroofIsSet = false;
}
bool Vehicle_1::isParkingSensors() const
{
    return m_Parking_sensors;
}
void Vehicle_1::setParkingSensors(bool const value)
{
    m_Parking_sensors = value;
    m_Parking_sensorsIsSet = true;
}
bool Vehicle_1::parkingSensorsIsSet() const
{
    return m_Parking_sensorsIsSet;
}
void Vehicle_1::unsetParking_sensors()
{
    m_Parking_sensorsIsSet = false;
}
double Vehicle_1::getBedLength() const
{
    return m_Bed_length;
}
void Vehicle_1::setBedLength(double const value)
{
    m_Bed_length = value;
}
double Vehicle_1::getTowingCapacity() const
{
    return m_Towing_capacity;
}
void Vehicle_1::setTowingCapacity(double const value)
{
    m_Towing_capacity = value;
}
double Vehicle_1::getPayloadCapacity() const
{
    return m_Payload_capacity;
}
void Vehicle_1::setPayloadCapacity(double const value)
{
    m_Payload_capacity = value;
}
double Vehicle_1::getEngineSize() const
{
    return m_Engine_size;
}
void Vehicle_1::setEngineSize(double const value)
{
    m_Engine_size = value;
}
bool Vehicle_1::isFourWheelDrive() const
{
    return m_Four_wheel_drive;
}
void Vehicle_1::setFourWheelDrive(bool const value)
{
    m_Four_wheel_drive = value;
    m_Four_wheel_driveIsSet = true;
}
bool Vehicle_1::fourWheelDriveIsSet() const
{
    return m_Four_wheel_driveIsSet;
}
void Vehicle_1::unsetFour_wheel_drive()
{
    m_Four_wheel_driveIsSet = false;
}
bool Vehicle_1::isBedLiner() const
{
    return m_Bed_liner;
}
void Vehicle_1::setBedLiner(bool const value)
{
    m_Bed_liner = value;
    m_Bed_linerIsSet = true;
}
bool Vehicle_1::bedLinerIsSet() const
{
    return m_Bed_linerIsSet;
}
void Vehicle_1::unsetBed_liner()
{
    m_Bed_linerIsSet = false;
}


} // namespace org::openapitools::server::model

