/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "VehicleResponseV2.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

VehicleResponseV2::VehicleResponseV2()
{
    m_Make = "";
    m_Model = "";
    m_Year = 0;
    m_Color = "";
    m_Vin = "";
    m_Registration_number = "";
    m_Insurance_expiryIsSet = false;
    m_Is_available = true;
    m_Is_availableIsSet = false;
    m_Id = "";
    m_Mileage = 0.0;
    m_Last_service_dateIsSet = false;
    
}

void VehicleResponseV2::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool VehicleResponseV2::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool VehicleResponseV2::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "VehicleResponseV2" : pathPrefix;

                         
    
    /* Vin */ {
        const std::string& value = m_Vin;
        const std::string currentValuePath = _pathPrefix + ".vin";
                
        
        if (value.length() < 17)
        {
            success = false;
            msg << currentValuePath << ": must be at least 17 characters long;";
        }
        if (value.length() > 17)
        {
            success = false;
            msg << currentValuePath << ": must be at most 17 characters long;";
        }

    }
                         
    
    /* Mileage */ {
        const double& value = m_Mileage;
        const std::string currentValuePath = _pathPrefix + ".mileage";
                
        
        if (value < 0.0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0.0;";
        }

    }
        
    return success;
}

bool VehicleResponseV2::operator==(const VehicleResponseV2& rhs) const
{
    return
    
    
    (getMake() == rhs.getMake())
     &&
    
    (getModel() == rhs.getModel())
     &&
    
    (getYear() == rhs.getYear())
     &&
    
    (getColor() == rhs.getColor())
     &&
    
    (getVin() == rhs.getVin())
     &&
    
    (getRegistrationNumber() == rhs.getRegistrationNumber())
     &&
    
    
    ((!insuranceExpiryIsSet() && !rhs.insuranceExpiryIsSet()) || (insuranceExpiryIsSet() && rhs.insuranceExpiryIsSet() && getInsuranceExpiry() == rhs.getInsuranceExpiry())) &&
    
    
    ((!isAvailableIsSet() && !rhs.isAvailableIsSet()) || (isAvailableIsSet() && rhs.isAvailableIsSet() && isIsAvailable() == rhs.isIsAvailable())) &&
    
    (getId() == rhs.getId())
     &&
    
    (getMileage() == rhs.getMileage())
     &&
    
    
    ((!lastServiceDateIsSet() && !rhs.lastServiceDateIsSet()) || (lastServiceDateIsSet() && rhs.lastServiceDateIsSet() && getLastServiceDate() == rhs.getLastServiceDate()))
    
    ;
}

bool VehicleResponseV2::operator!=(const VehicleResponseV2& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const VehicleResponseV2& o)
{
    j = nlohmann::json::object();
    j["make"] = o.m_Make;
    j["model"] = o.m_Model;
    j["year"] = o.m_Year;
    j["color"] = o.m_Color;
    j["vin"] = o.m_Vin;
    j["registration_number"] = o.m_Registration_number;
    if(o.insuranceExpiryIsSet())
        j["insurance_expiry"] = o.m_Insurance_expiry;
    if(o.isAvailableIsSet())
        j["is_available"] = o.m_Is_available;
    j["id"] = o.m_Id;
    j["mileage"] = o.m_Mileage;
    if(o.lastServiceDateIsSet())
        j["last_service_date"] = o.m_Last_service_date;
    
}

void from_json(const nlohmann::json& j, VehicleResponseV2& o)
{
    j.at("make").get_to(o.m_Make);
    j.at("model").get_to(o.m_Model);
    j.at("year").get_to(o.m_Year);
    j.at("color").get_to(o.m_Color);
    j.at("vin").get_to(o.m_Vin);
    j.at("registration_number").get_to(o.m_Registration_number);
    if(j.find("insurance_expiry") != j.end())
    {
        j.at("insurance_expiry").get_to(o.m_Insurance_expiry);
        o.m_Insurance_expiryIsSet = true;
    } 
    if(j.find("is_available") != j.end())
    {
        j.at("is_available").get_to(o.m_Is_available);
        o.m_Is_availableIsSet = true;
    } 
    j.at("id").get_to(o.m_Id);
    j.at("mileage").get_to(o.m_Mileage);
    if(j.find("last_service_date") != j.end())
    {
        j.at("last_service_date").get_to(o.m_Last_service_date);
        o.m_Last_service_dateIsSet = true;
    } 
    
}

std::string VehicleResponseV2::getMake() const
{
    return m_Make;
}
void VehicleResponseV2::setMake(std::string const& value)
{
    m_Make = value;
}
std::string VehicleResponseV2::getModel() const
{
    return m_Model;
}
void VehicleResponseV2::setModel(std::string const& value)
{
    m_Model = value;
}
int32_t VehicleResponseV2::getYear() const
{
    return m_Year;
}
void VehicleResponseV2::setYear(int32_t const value)
{
    m_Year = value;
}
std::string VehicleResponseV2::getColor() const
{
    return m_Color;
}
void VehicleResponseV2::setColor(std::string const& value)
{
    m_Color = value;
}
std::string VehicleResponseV2::getVin() const
{
    return m_Vin;
}
void VehicleResponseV2::setVin(std::string const& value)
{
    m_Vin = value;
}
std::string VehicleResponseV2::getRegistrationNumber() const
{
    return m_Registration_number;
}
void VehicleResponseV2::setRegistrationNumber(std::string const& value)
{
    m_Registration_number = value;
}
std::string VehicleResponseV2::getInsuranceExpiry() const
{
    return m_Insurance_expiry;
}
void VehicleResponseV2::setInsuranceExpiry(std::string const& value)
{
    m_Insurance_expiry = value;
    m_Insurance_expiryIsSet = true;
}
bool VehicleResponseV2::insuranceExpiryIsSet() const
{
    return m_Insurance_expiryIsSet;
}
void VehicleResponseV2::unsetInsurance_expiry()
{
    m_Insurance_expiryIsSet = false;
}
bool VehicleResponseV2::isIsAvailable() const
{
    return m_Is_available;
}
void VehicleResponseV2::setIsAvailable(bool const value)
{
    m_Is_available = value;
    m_Is_availableIsSet = true;
}
bool VehicleResponseV2::isAvailableIsSet() const
{
    return m_Is_availableIsSet;
}
void VehicleResponseV2::unsetIs_available()
{
    m_Is_availableIsSet = false;
}
std::string VehicleResponseV2::getId() const
{
    return m_Id;
}
void VehicleResponseV2::setId(std::string const& value)
{
    m_Id = value;
}
double VehicleResponseV2::getMileage() const
{
    return m_Mileage;
}
void VehicleResponseV2::setMileage(double const value)
{
    m_Mileage = value;
}
std::string VehicleResponseV2::getLastServiceDate() const
{
    return m_Last_service_date;
}
void VehicleResponseV2::setLastServiceDate(std::string const& value)
{
    m_Last_service_date = value;
    m_Last_service_dateIsSet = true;
}
bool VehicleResponseV2::lastServiceDateIsSet() const
{
    return m_Last_service_dateIsSet;
}
void VehicleResponseV2::unsetLast_service_date()
{
    m_Last_service_dateIsSet = false;
}


} // namespace org::openapitools::server::model

