/**
* System Designer Schemas
* JSON schemas for the System Designer project
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Vehicle.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

Vehicle::Vehicle()
{
    m_Make = "";
    m_Model = "";
    m_Year = 0;
    m_Color = "";
    m_Vin = "";
    m_Mileage = 0.0;
    m_Last_service_dateIsSet = false;
    m_Doors = 0;
    m_Trunk_capacity = 0.0;
    m_Bed_length = 0.0;
    m_Towing_capacity = 0.0;
    m_Payload_capacity = 0.0;
    m_Engine_size = 0.0;
    
}

void Vehicle::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool Vehicle::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool Vehicle::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "Vehicle" : pathPrefix;

                         
    
    /* Vin */ {
        const std::string& value = m_Vin;
        const std::string currentValuePath = _pathPrefix + ".vin";
                
        
        if (value.length() < 17)
        {
            success = false;
            msg << currentValuePath << ": must be at least 17 characters long;";
        }
        if (value.length() > 17)
        {
            success = false;
            msg << currentValuePath << ": must be at most 17 characters long;";
        }

    }
         
    
    /* Mileage */ {
        const double& value = m_Mileage;
        const std::string currentValuePath = _pathPrefix + ".mileage";
                
        
        if (value < 0.0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0.0;";
        }

    }
             
    
    /* Doors */ {
        const int32_t& value = m_Doors;
        const std::string currentValuePath = _pathPrefix + ".doors";
                
        
        if (value < 2)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 2;";
        }
        if (value > 5)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 5;";
        }

    }
         
    
    /* Trunk_capacity */ {
        const double& value = m_Trunk_capacity;
        const std::string currentValuePath = _pathPrefix + ".trunkCapacity";
                
        
        if (value < 0.0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0.0;";
        }
        if (value > 100.0)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 100.0;";
        }

    }
                     
    
    /* Towing_capacity */ {
        const double& value = m_Towing_capacity;
        const std::string currentValuePath = _pathPrefix + ".towingCapacity";
                
        
        if (value < 0.0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0.0;";
        }
        if (value > 100000.0)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 100000.0;";
        }

    }
            
    return success;
}

bool Vehicle::operator==(const Vehicle& rhs) const
{
    return
    
    
    (getMake() == rhs.getMake())
     &&
    
    (getModel() == rhs.getModel())
     &&
    
    (getYear() == rhs.getYear())
     &&
    
    (getColor() == rhs.getColor())
     &&
    
    (getVin() == rhs.getVin())
     &&
    
    (getMileage() == rhs.getMileage())
     &&
    
    
    ((!lastServiceDateIsSet() && !rhs.lastServiceDateIsSet()) || (lastServiceDateIsSet() && rhs.lastServiceDateIsSet() && getLastServiceDate() == rhs.getLastServiceDate())) &&
    
    (getDoors() == rhs.getDoors())
     &&
    
    (getTrunkCapacity() == rhs.getTrunkCapacity())
     &&
    
    (getFuelType() == rhs.getFuelType())
     &&
    
    (getTransmission() == rhs.getTransmission())
     &&
    
    (getBedLength() == rhs.getBedLength())
     &&
    
    (getTowingCapacity() == rhs.getTowingCapacity())
     &&
    
    (getPayloadCapacity() == rhs.getPayloadCapacity())
     &&
    
    (getEngineSize() == rhs.getEngineSize())
    
    
    ;
}

bool Vehicle::operator!=(const Vehicle& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Vehicle& o)
{
    j = nlohmann::json::object();
    j["make"] = o.m_Make;
    j["model"] = o.m_Model;
    j["year"] = o.m_Year;
    j["color"] = o.m_Color;
    j["vin"] = o.m_Vin;
    j["mileage"] = o.m_Mileage;
    if(o.lastServiceDateIsSet())
        j["last_service_date"] = o.m_Last_service_date;
    j["doors"] = o.m_Doors;
    j["trunk_capacity"] = o.m_Trunk_capacity;
    j["fuel_type"] = o.m_Fuel_type;
    j["transmission"] = o.m_Transmission;
    j["bed_length"] = o.m_Bed_length;
    j["towing_capacity"] = o.m_Towing_capacity;
    j["payload_capacity"] = o.m_Payload_capacity;
    j["engine_size"] = o.m_Engine_size;
    
}

void from_json(const nlohmann::json& j, Vehicle& o)
{
    j.at("make").get_to(o.m_Make);
    j.at("model").get_to(o.m_Model);
    j.at("year").get_to(o.m_Year);
    j.at("color").get_to(o.m_Color);
    j.at("vin").get_to(o.m_Vin);
    j.at("mileage").get_to(o.m_Mileage);
    if(j.find("last_service_date") != j.end())
    {
        j.at("last_service_date").get_to(o.m_Last_service_date);
        o.m_Last_service_dateIsSet = true;
    } 
    j.at("doors").get_to(o.m_Doors);
    j.at("trunk_capacity").get_to(o.m_Trunk_capacity);
    j.at("fuel_type").get_to(o.m_Fuel_type);
    j.at("transmission").get_to(o.m_Transmission);
    j.at("bed_length").get_to(o.m_Bed_length);
    j.at("towing_capacity").get_to(o.m_Towing_capacity);
    j.at("payload_capacity").get_to(o.m_Payload_capacity);
    j.at("engine_size").get_to(o.m_Engine_size);
    
}

std::string Vehicle::getMake() const
{
    return m_Make;
}
void Vehicle::setMake(std::string const& value)
{
    m_Make = value;
}
std::string Vehicle::getModel() const
{
    return m_Model;
}
void Vehicle::setModel(std::string const& value)
{
    m_Model = value;
}
int32_t Vehicle::getYear() const
{
    return m_Year;
}
void Vehicle::setYear(int32_t const value)
{
    m_Year = value;
}
std::string Vehicle::getColor() const
{
    return m_Color;
}
void Vehicle::setColor(std::string const& value)
{
    m_Color = value;
}
std::string Vehicle::getVin() const
{
    return m_Vin;
}
void Vehicle::setVin(std::string const& value)
{
    m_Vin = value;
}
double Vehicle::getMileage() const
{
    return m_Mileage;
}
void Vehicle::setMileage(double const value)
{
    m_Mileage = value;
}
std::string Vehicle::getLastServiceDate() const
{
    return m_Last_service_date;
}
void Vehicle::setLastServiceDate(std::string const& value)
{
    m_Last_service_date = value;
    m_Last_service_dateIsSet = true;
}
bool Vehicle::lastServiceDateIsSet() const
{
    return m_Last_service_dateIsSet;
}
void Vehicle::unsetLast_service_date()
{
    m_Last_service_dateIsSet = false;
}
int32_t Vehicle::getDoors() const
{
    return m_Doors;
}
void Vehicle::setDoors(int32_t const value)
{
    m_Doors = value;
}
double Vehicle::getTrunkCapacity() const
{
    return m_Trunk_capacity;
}
void Vehicle::setTrunkCapacity(double const value)
{
    m_Trunk_capacity = value;
}
org::openapitools::server::model::FuelType Vehicle::getFuelType() const
{
    return m_Fuel_type;
}
void Vehicle::setFuelType(org::openapitools::server::model::FuelType const& value)
{
    m_Fuel_type = value;
}
org::openapitools::server::model::TransmissionType Vehicle::getTransmission() const
{
    return m_Transmission;
}
void Vehicle::setTransmission(org::openapitools::server::model::TransmissionType const& value)
{
    m_Transmission = value;
}
double Vehicle::getBedLength() const
{
    return m_Bed_length;
}
void Vehicle::setBedLength(double const value)
{
    m_Bed_length = value;
}
double Vehicle::getTowingCapacity() const
{
    return m_Towing_capacity;
}
void Vehicle::setTowingCapacity(double const value)
{
    m_Towing_capacity = value;
}
double Vehicle::getPayloadCapacity() const
{
    return m_Payload_capacity;
}
void Vehicle::setPayloadCapacity(double const value)
{
    m_Payload_capacity = value;
}
double Vehicle::getEngineSize() const
{
    return m_Engine_size;
}
void Vehicle::setEngineSize(double const value)
{
    m_Engine_size = value;
}


} // namespace org::openapitools::server::model

