// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetVehiclesV1ApiV1VehiclesGetData, GetVehiclesV1ApiV1VehiclesGetResponse, CreateVehicleV1ApiV1VehiclesPostData, CreateVehicleV1ApiV1VehiclesPostResponse, CreateVehicleV1ApiV1VehiclesPostError, GetCarsV1ApiV1CarsGetData, GetCarsV1ApiV1CarsGetResponse, CreateCarV1ApiV1CarsPostData, CreateCarV1ApiV1CarsPostResponse, CreateCarV1ApiV1CarsPostError, GetTrucksV1ApiV1TrucksGetData, GetTrucksV1ApiV1TrucksGetResponse, CreateTruckV1ApiV1TrucksPostData, CreateTruckV1ApiV1TrucksPostResponse, CreateTruckV1ApiV1TrucksPostError, GetVehiclesV2ApiV2VehiclesGetData, GetVehiclesV2ApiV2VehiclesGetResponse, CreateVehicleV2ApiV2VehiclesPostData, CreateVehicleV2ApiV2VehiclesPostResponse, CreateVehicleV2ApiV2VehiclesPostError, GetCarsV2ApiV2CarsGetData, GetCarsV2ApiV2CarsGetResponse, CreateCarV2ApiV2CarsPostData, CreateCarV2ApiV2CarsPostResponse, CreateCarV2ApiV2CarsPostError, GetTrucksV2ApiV2TrucksGetData, GetTrucksV2ApiV2TrucksGetResponse, CreateTruckV2ApiV2TrucksPostData, CreateTruckV2ApiV2TrucksPostResponse, CreateTruckV2ApiV2TrucksPostError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Vehicles V1
 * Retrieve a list of vehicles (V1).
 */
export const getVehiclesV1ApiV1VehiclesGet = <ThrowOnError extends boolean = false>(options?: Options<GetVehiclesV1ApiV1VehiclesGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetVehiclesV1ApiV1VehiclesGetResponse, unknown, ThrowOnError>({
        url: '/api/v1/vehicles',
        ...options
    });
};

/**
 * Create Vehicle V1
 * Create a new vehicle (V1).
 */
export const createVehicleV1ApiV1VehiclesPost = <ThrowOnError extends boolean = false>(options: Options<CreateVehicleV1ApiV1VehiclesPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateVehicleV1ApiV1VehiclesPostResponse, CreateVehicleV1ApiV1VehiclesPostError, ThrowOnError>({
        url: '/api/v1/vehicles',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Cars V1
 * Retrieve a list of cars (V1).
 */
export const getCarsV1ApiV1CarsGet = <ThrowOnError extends boolean = false>(options?: Options<GetCarsV1ApiV1CarsGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCarsV1ApiV1CarsGetResponse, unknown, ThrowOnError>({
        url: '/api/v1/cars',
        ...options
    });
};

/**
 * Create Car V1
 * Create a new car (V1).
 */
export const createCarV1ApiV1CarsPost = <ThrowOnError extends boolean = false>(options: Options<CreateCarV1ApiV1CarsPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateCarV1ApiV1CarsPostResponse, CreateCarV1ApiV1CarsPostError, ThrowOnError>({
        url: '/api/v1/cars',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Trucks V1
 * Retrieve a list of trucks (V1).
 */
export const getTrucksV1ApiV1TrucksGet = <ThrowOnError extends boolean = false>(options?: Options<GetTrucksV1ApiV1TrucksGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetTrucksV1ApiV1TrucksGetResponse, unknown, ThrowOnError>({
        url: '/api/v1/trucks',
        ...options
    });
};

/**
 * Create Truck V1
 * Create a new truck (V1).
 */
export const createTruckV1ApiV1TrucksPost = <ThrowOnError extends boolean = false>(options: Options<CreateTruckV1ApiV1TrucksPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateTruckV1ApiV1TrucksPostResponse, CreateTruckV1ApiV1TrucksPostError, ThrowOnError>({
        url: '/api/v1/trucks',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Vehicles V2
 * Retrieve a list of vehicles (V2).
 */
export const getVehiclesV2ApiV2VehiclesGet = <ThrowOnError extends boolean = false>(options?: Options<GetVehiclesV2ApiV2VehiclesGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetVehiclesV2ApiV2VehiclesGetResponse, unknown, ThrowOnError>({
        url: '/api/v2/vehicles',
        ...options
    });
};

/**
 * Create Vehicle V2
 * Create a new vehicle (V2).
 */
export const createVehicleV2ApiV2VehiclesPost = <ThrowOnError extends boolean = false>(options: Options<CreateVehicleV2ApiV2VehiclesPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateVehicleV2ApiV2VehiclesPostResponse, CreateVehicleV2ApiV2VehiclesPostError, ThrowOnError>({
        url: '/api/v2/vehicles',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Cars V2
 * Retrieve a list of cars (V2).
 */
export const getCarsV2ApiV2CarsGet = <ThrowOnError extends boolean = false>(options?: Options<GetCarsV2ApiV2CarsGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCarsV2ApiV2CarsGetResponse, unknown, ThrowOnError>({
        url: '/api/v2/cars',
        ...options
    });
};

/**
 * Create Car V2
 * Create a new car (V2).
 */
export const createCarV2ApiV2CarsPost = <ThrowOnError extends boolean = false>(options: Options<CreateCarV2ApiV2CarsPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateCarV2ApiV2CarsPostResponse, CreateCarV2ApiV2CarsPostError, ThrowOnError>({
        url: '/api/v2/cars',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Trucks V2
 * Retrieve a list of trucks (V2).
 */
export const getTrucksV2ApiV2TrucksGet = <ThrowOnError extends boolean = false>(options?: Options<GetTrucksV2ApiV2TrucksGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetTrucksV2ApiV2TrucksGetResponse, unknown, ThrowOnError>({
        url: '/api/v2/trucks',
        ...options
    });
};

/**
 * Create Truck V2
 * Create a new truck (V2).
 */
export const createTruckV2ApiV2TrucksPost = <ThrowOnError extends boolean = false>(options: Options<CreateTruckV2ApiV2TrucksPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateTruckV2ApiV2TrucksPostResponse, CreateTruckV2ApiV2TrucksPostError, ThrowOnError>({
        url: '/api/v2/trucks',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};